-- GENERATED by tools/sculpt/library.py — do not edit. Mesh library manifest:
-- every component's MeshPart pieces (name, palette role, offset, size), sockets, layout.
return {
	components = {
		Antler = {
			grade = "Grade2",
			pieces = {
				{
					name = "Antler_BoneDark",
					offset = { 0.1978, 0.6797, 0.2399 },
					role = "BoneDark",
					size = { 0.6433, 1.613, 0.7273 },
					tris = 2289,
				},
				{
					name = "Antler_Skin",
					offset = { 0.001, -0.0546, 0.0011 },
					role = "Skin",
					size = { 0.256, 0.1286, 0.255 },
					tris = 211,
				},
			},
			sided = True,
			slot = "Horns",
			socket = "Crown",
			space = "surface",
			tags = { "horn", "bone" },
		},
		BackHorn = {
			grade = "Grade3",
			pieces = {
				{
					name = "BackHorn_Bone",
					offset = { 0.1114, 0.2855, 0.6166 },
					role = "Bone",
					size = { 0.3902, 0.3875, 1.004 },
					tris = 1309,
				},
				{
					name = "BackHorn_BoneDark",
					offset = { 0.0101, 0.0551, 0.0488 },
					role = "BoneDark",
					size = { 0.3171, 0.4269, 0.4403 },
					tris = 548,
				},
				{
					name = "BackHorn_Claw",
					offset = { 0.27, 0.4208, 1.079 },
					role = "Claw",
					size = { 0.1296, 0.0963, 0.2559 },
					tris = 179,
				},
				{
					name = "BackHorn_Skin",
					offset = { 0.0001, -0.048, -0.001 },
					role = "Skin",
					size = { 0.3626, 0.1837, 0.3661 },
					tris = 464,
				},
			},
			sided = True,
			slot = "Horns",
			socket = "Crown",
			space = "surface",
			tags = { "horn", "bone" },
		},
		BeastHead = {
			defaults = {
				Eyes = {
					{
						id = "Eye",
						socket = "EyeR",
					},
					{
						id = "Eye",
						socket = "EyeL",
					},
				},
				Mouths = {  },
			},
			grade = "Grade4",
			pieces = {
				{
					name = "BeastHead_Skin",
					offset = { -0.0018, 0.0366, -0.193 },
					role = "Skin",
					size = { 1.034, 1.33, 1.953 },
					tris = 3323,
				},
				{
					name = "BeastHead_SkinDark",
					offset = { 0.0017, 0.2625, -0.2408 },
					role = "SkinDark",
					size = { 1.04, 1.662, 1.614 },
					tris = 1623,
				},
				{
					name = "BeastHead_SkinDeep",
					offset = { 0.0023, 0.2744, -0.344 },
					role = "SkinDeep",
					size = { 0.7835, 0.2163, 0.2196 },
					tris = 313,
				},
				{
					name = "BeastHead_SkinLight",
					offset = { 0.0005, 0.2562, -0.4908 },
					role = "SkinLight",
					size = { 0.8019, 0.3795, 0.5262 },
					tris = 469,
				},
				{
					name = "BeastHead_Teeth",
					offset = { 0.0029, -0.2535, -0.538 },
					role = "Teeth",
					size = { 0.3818, 0.0867, 0.3684 },
					tris = 191,
				},
				{
					name = "BeastHead_Void",
					offset = { -0.0015, -0.1848, -0.6861 },
					role = "Void",
					size = { 0.4893, 0.2741, 0.8469 },
					tris = 1079,
				},
			},
			sided = False,
			slot = "Head",
			sockets = {
				Crown = {
					pos = { 0, 0.72, 0.2 },
					rot = { 0, 0, 0 },
				},
				Brow = {
					pos = { 0, 0.45, -0.3 },
					rot = { -60, 0, 0 },
				},
				Face = {
					pos = { 0, 0.05, -0.9 },
					rot = { -90, 0, 0 },
				},
				Mouth = {
					pos = { 0, -0.3, -0.92 },
					rot = { -90, 0, 0 },
				},
				Jaw = {
					pos = { 0, -0.55, -0.6 },
					rot = { 180, 0, 0 },
				},
				BackOfHead = {
					pos = { 0, 0.3, 0.8 },
					rot = { 90, 0, 0 },
				},
				TopR = {
					pos = { 0.3, 0.62, 0.12 },
					rot = { 0, 0, -25 },
				},
				TopL = {
					pos = { -0.3, 0.62, 0.12 },
					rot = { 0, 0, 25 },
				},
				EyeR = {
					pos = { 0.3, 0.28, -0.32 },
					rot = { -90, 0, -35 },
				},
				EyeL = {
					pos = { -0.3, 0.28, -0.32 },
					rot = { -90, 0, 35 },
				},
				CheekR = {
					pos = { 0.4, -0.05, -0.4 },
					rot = { -90, 0, -45 },
				},
				CheekL = {
					pos = { -0.4, -0.05, -0.4 },
					rot = { -90, 0, 45 },
				},
				TempleR = {
					pos = { 0.5, 0.3, 0.15 },
					rot = { 0, 0, -90 },
				},
				TempleL = {
					pos = { -0.5, 0.3, 0.15 },
					rot = { 0, 0, 90 },
				},
				EarR = {
					pos = { 0.45, 0.45, 0.35 },
					rot = { 0, 0, -90 },
				},
				EarL = {
					pos = { -0.45, 0.45, 0.35 },
					rot = { 0, 0, 90 },
				},
			},
			space = "head",
			tags = { "beast" },
		},
		BladeTail = {
			grade = "Grade2",
			pieces = {
				{
					name = "BladeTail_Bone",
					offset = { 0.1331, -0.3486, 1.529 },
					role = "Bone",
					size = { 0.1404, 0.5113, 0.8142 },
					tris = 117,
				},
				{
					name = "BladeTail_Claw",
					offset = { 0.2005, -0.9767, 2.554 },
					role = "Claw",
					size = { 0.1492, 0.4245, 0.8384 },
					tris = 527,
				},
				{
					name = "BladeTail_Skin",
					offset = { 0.0191, -0.3696, 1.018 },
					role = "Skin",
					size = { 0.5193, 1.221, 2.517 },
					tris = 2856,
				},
			},
			sided = False,
			slot = "Tails",
			socket = "TailRoot",
			space = "body",
			tags = { "tail", "blade" },
		},
		BladedHand = {
			grade = "Grade2",
			pieces = {
				{
					name = "BladedHand_Claw",
					offset = { -0.0002, -0.9012, -0.0051 },
					role = "Claw",
					size = { 0.0814, 0.8232, 0.5281 },
					tris = 1200,
				},
				{
					name = "BladedHand_Skin",
					offset = { -0.0457, -0.3148, -0.056 },
					role = "Skin",
					size = { 0.3941, 0.6725, 0.6194 },
					tris = 2120,
				},
				{
					name = "BladedHand_SkinLight",
					offset = { 0.0533, -0.3855, 0.0004 },
					role = "SkinLight",
					size = { 0.1207, 0.1581, 0.4985 },
					tris = 178,
				},
			},
			sided = True,
			slot = "Hands",
			space = "hand",
			tags = { "hand", "blade" },
		},
		BoneArm = {
			grade = "Grade2",
			pieces = {
				{
					name = "BoneArm_Bone",
					offset = { -0.339, -0.3856, 0.0111 },
					role = "Bone",
					size = { 0.3148, 1.293, 0.3054 },
					tris = 1103,
				},
				{
					name = "BoneArm_BoneDark",
					offset = { -0.3162, -0.6811, -0.0093 },
					role = "BoneDark",
					size = { 0.278, 0.8975, 0.3815 },
					tris = 1222,
				},
				{
					name = "BoneArm_SkinDark",
					offset = { -0.4, 0.2432, -0 },
					role = "SkinDark",
					size = { 0.6005, 1.034, 0.6003 },
					tris = 2675,
				},
			},
			pivot = { -0.5, 0.5, 0 },
			sided = True,
			slot = "Arms",
			sockets = {
				Shoulder = {
					pos = { -0.42, 0.72, 0 },
					rot = { 0, 0, 0 },
				},
				UpperArm = {
					pos = { -0.2194, 0.035, 0 },
					rot = { 0, 0, -90 },
				},
				Elbow = {
					pos = { -0.33, -0.35, 0.1896 },
					rot = { 90, 0, 0 },
				},
				Forearm = {
					pos = { -0.1854, -0.7, -0.01 },
					rot = { 0, 0, -90 },
				},
				Hand = {
					pos = { -0.3, -1.1, -0.08 },
					rot = { 0, 0, 0 },
				},
				Palm = {
					pos = { -0.45, -1.35, -0.08 },
					rot = { 0, 0, 90 },
				},
			},
			space = "arm",
			tags = { "arm", "bone" },
		},
		BoneProtrusion = {
			grade = "Grade3",
			pieces = {
				{
					name = "BoneProtrusion_Bone",
					offset = { 0.0128, 0.2294, 0.0325 },
					role = "Bone",
					size = { 0.1831, 0.7378, 0.2315 },
					tris = 725,
				},
				{
					name = "BoneProtrusion_BoneDark",
					offset = { 0.0797, 0.5963, 0.1199 },
					role = "BoneDark",
					size = { 0.0709, 0.0776, 0.0708 },
					tris = 124,
				},
				{
					name = "BoneProtrusion_Flesh",
					offset = { 0.0018, 0.0471, -0.0008 },
					role = "Flesh",
					size = { 0.4311, 0.0797, 0.4314 },
					tris = 552,
				},
				{
					name = "BoneProtrusion_SkinDark",
					offset = { 0.0001, -0.0348, 0.0001 },
					role = "SkinDark",
					size = { 0.4785, 0.1748, 0.4802 },
					tris = 1099,
				},
			},
			sided = False,
			slot = "Disfigurements",
			socket = "Forearm_R",
			space = "surface",
			tags = { "bone", "wound" },
		},
		BoneSpur = {
			grade = "Grade4",
			pieces = {
				{
					name = "BoneSpur_Bone",
					offset = { -0.0003, 0.2684, 0.0462 },
					role = "Bone",
					size = { 0.1011, 0.2821, 0.1553 },
					tris = 456,
				},
				{
					name = "BoneSpur_BoneDark",
					offset = { -0.0026, 0.0276, 0.0049 },
					role = "BoneDark",
					size = { 0.2017, 0.2922, 0.207 },
					tris = 483,
				},
				{
					name = "BoneSpur_Skin",
					offset = { -0, -0.0487, 0.0001 },
					role = "Skin",
					size = { 0.2293, 0.1195, 0.2294 },
					tris = 559,
				},
			},
			sided = False,
			slot = "Disfigurements",
			slots = { "HeadGrowths", "Disfigurements", "TorsoGrowths" },
			socket = "BackOfHead",
			space = "surface",
			tags = { "bone" },
		},
		BoneTail = {
			grade = "Grade2",
			pieces = {
				{
					name = "BoneTail_Bone",
					offset = { 0.0332, -0.5685, 0.9013 },
					role = "Bone",
					size = { 0.4481, 1.476, 2.183 },
					tris = 3213,
				},
				{
					name = "BoneTail_BoneDark",
					offset = { 0.0799, -0.4274, 1.026 },
					role = "BoneDark",
					size = { 0.2835, 1.627, 2.075 },
					tris = 542,
				},
				{
					name = "BoneTail_SkinDark",
					offset = { 0.1484, -1.113, 1.766 },
					role = "SkinDark",
					size = { 0.1812, 0.6345, 0.5301 },
					tris = 245,
				},
			},
			sided = False,
			slot = "Tails",
			socket = "TailRoot",
			space = "body",
			tags = { "tail", "bone" },
		},
		BoneWing = {
			grade = "Grade1",
			joint = True,
			pieces = {
				{
					name = "BoneWing_Bone",
					offset = { 1.364, 0.3235, 0.5652 },
					role = "Bone",
					size = { 2.575, 2.077, 1.097 },
					tris = 3160,
				},
				{
					name = "BoneWing_BoneDark",
					offset = { 2.12, 0.3713, 0.9308 },
					role = "BoneDark",
					size = { 1.271, 2.269, 0.3931 },
					tris = 162,
				},
				{
					name = "BoneWing_Skin",
					offset = { 0.004, 0.0506, 0.0501 },
					role = "Skin",
					size = { 0.5303, 0.48, 0.5603 },
					tris = 676,
				},
			},
			sided = True,
			slot = "Back",
			socket = "BackR",
			space = "body",
			tags = { "wing", "bone" },
		},
		BrokenHorn = {
			grade = "Grade3",
			pieces = {
				{
					name = "BrokenHorn_Bone",
					offset = { 0.0611, 0.3573, 0.0232 },
					role = "Bone",
					size = { 0.2731, 0.3173, 0.235 },
					tris = 705,
				},
				{
					name = "BrokenHorn_BoneDark",
					offset = { 0.0087, 0.1723, 0 },
					role = "BoneDark",
					size = { 0.366, 0.6872, 0.3109 },
					tris = 1002,
				},
				{
					name = "BrokenHorn_Skin",
					offset = { -0.0004, -0.0536, -0.0001 },
					role = "Skin",
					size = { 0.392, 0.1749, 0.3921 },
					tris = 793,
				},
			},
			sided = True,
			slot = "Horns",
			socket = "Crown",
			space = "surface",
			tags = { "horn", "bone" },
		},
		ClawedFoot = {
			grade = "Grade3",
			pieces = {
				{
					name = "ClawedFoot_Claw",
					offset = { 0.0003, 0.051, -0.7202 },
					role = "Claw",
					size = { 0.3992, 0.1275, 0.199 },
					tris = 620,
				},
				{
					name = "ClawedFoot_Skin",
					offset = { -0.0007, 0.1382, -0.1862 },
					role = "Skin",
					size = { 0.4385, 0.2849, 0.973 },
					tris = 2378,
				},
			},
			sided = True,
			slot = "Feet",
			space = "foot",
			tags = { "foot", "claw" },
		},
		ClawedHand = {
			grade = "Grade3",
			pieces = {
				{
					name = "ClawedHand_Claw",
					offset = { -0.1822, -0.6611, -0.0337 },
					role = "Claw",
					size = { 0.2308, 0.4868, 0.5492 },
					tris = 764,
				},
				{
					name = "ClawedHand_Skin",
					offset = { -0.0481, -0.3735, -0.0582 },
					role = "Skin",
					size = { 0.3984, 0.7921, 0.6157 },
					tris = 2568,
				},
				{
					name = "ClawedHand_SkinLight",
					offset = { 0.0467, -0.381, 0.0012 },
					role = "SkinLight",
					size = { 0.1317, 0.1616, 0.4969 },
					tris = 166,
				},
			},
			sided = True,
			slot = "Hands",
			space = "hand",
			tags = { "hand", "claw" },
		},
		CompoundEye = {
			grade = "Grade3",
			pieces = {
				{
					name = "CompoundEye_Void",
					offset = { 0.0003, 0.0199, 0 },
					role = "Void",
					size = { 0.4799, 0.4003, 0.5601 },
					tris = 1500,
				},
			},
			sided = False,
			slot = "Eyes",
			slots = { "Eyes", "Disfigurements" },
			socket = "Face",
			space = "surface",
			tags = { "eye", "insect" },
		},
		CrackedFlesh = {
			grade = "Grade3",
			pieces = {
				{
					name = "CrackedFlesh_Glow",
					offset = { -0.0812, 0.0224, 0.0376 },
					role = "Glow",
					size = { 0.6307, 0.0499, 0.477 },
					tris = 539,
				},
				{
					name = "CrackedFlesh_Skin",
					offset = { 0.0001, -0.0404, 0.0001 },
					role = "Skin",
					size = { 0.8382, 0.1796, 0.839 },
					tris = 1928,
				},
				{
					name = "CrackedFlesh_VoidRim",
					offset = { -0.0192, 0.0308, -0.0164 },
					role = "VoidRim",
					size = { 0.5958, 0.0372, 0.4709 },
					tris = 531,
				},
			},
			sided = False,
			slot = "Disfigurements",
			socket = "ChestR",
			space = "surface",
			tags = { "wound", "energy" },
		},
		CurvedHorn = {
			grade = "Grade3",
			pieces = {
				{
					name = "CurvedHorn_Bone",
					offset = { 0.4354, 0.4211, 0.1987 },
					role = "Bone",
					size = { 0.8801, 0.5233, 0.5297 },
					tris = 1515,
				},
				{
					name = "CurvedHorn_BoneDark",
					offset = { 0.0075, 0.0663, -0.0073 },
					role = "BoneDark",
					size = { 0.3577, 0.4553, 0.3022 },
					tris = 527,
				},
				{
					name = "CurvedHorn_Skin",
					offset = { -0.0005, -0.051, 0.0003 },
					role = "Skin",
					size = { 0.363, 0.1764, 0.3641 },
					tris = 458,
				},
			},
			sided = True,
			slot = "Horns",
			socket = "Crown",
			space = "surface",
			tags = { "horn", "bone" },
		},
		DigitigradeLeg = {
			grade = "Grade2",
			legExtra = 0.2,
			pieces = {
				{
					name = "DigitigradeLeg_Skin",
					offset = { 0.0097, 0.2304, -0.012 },
					role = "Skin",
					size = { 0.7826, 1.881, 1.138 },
					tris = 4248,
				},
				{
					name = "DigitigradeLeg_SkinDark",
					offset = { -0.0086, -0.7181, 0.1786 },
					role = "SkinDark",
					size = { 0.294, 0.5828, 0.7569 },
					tris = 752,
				},
			},
			pivot = { 0.5, 1, 0 },
			sided = True,
			slot = "Legs",
			sockets = {
				Thigh = {
					pos = { 0.01, 0.4, -0.3375 },
					rot = { -90, 0, 0 },
				},
				Knee = {
					pos = { 0, 0.05, -0.575 },
					rot = { -90, 0, 0 },
				},
				Shin = {
					pos = { 0.225, -0.25, 0.025 },
					rot = { 0, 0, -90 },
				},
				Foot = {
					pos = { 0, -1, -0.14 },
					rot = { 0, 0, 0 },
				},
			},
			space = "leg",
			span = 2,
			tags = { "leg", "beast" },
		},
		EmaciatedTorso = {
			grade = "Grade4",
			hidden = False,
			layout = {
				neck = { 0, 1, -0.03 },
				shoulder = { 0.85, 0.6, 0 },
				hip = { 0.9, -1, 0 },
				tailRoot = { 0, -0.8, 0.35 },
				legExtra = 0.1,
			},
			pieces = {
				{
					name = "EmaciatedTorso_Skin",
					offset = { 0.0025, 0.0339, -0.0049 },
					role = "Skin",
					size = { 1.723, 2.411, 0.8498 },
					tris = 3716,
				},
				{
					name = "EmaciatedTorso_SkinLight",
					offset = { 0.0069, 0.0434, -0.0058 },
					role = "SkinLight",
					size = { 1.409, 1.934, 0.8515 },
					tris = 4284,
				},
			},
			sided = False,
			slot = "Torso",
			sockets = {
				Chest = {
					pos = { 0, 0.3, -0.42 },
					rot = { -90, 0, 0 },
				},
				Belly = {
					pos = { 0, -0.35, -0.378 },
					rot = { -90, 0, 0 },
				},
				UpperBack = {
					pos = { 0, 0.6, 0.42 },
					rot = { 90, 0, 0 },
				},
				Back = {
					pos = { 0, 0.15, 0.4284 },
					rot = { 90, 0, 0 },
				},
				LowerBack = {
					pos = { 0, -0.4, 0.378 },
					rot = { 90, 0, 0 },
				},
				TailRoot = {
					pos = { 0, -0.8, 0.42 },
					rot = { 90, 0, 0 },
				},
				Neck = {
					pos = { 0, 1, 0.05 },
					rot = { 0, 0, 0 },
				},
				ChestR = {
					pos = { 0.272, 0.45, -0.399 },
					rot = { -90, 0, 0 },
				},
				ChestL = {
					pos = { -0.272, 0.45, -0.399 },
					rot = { -90, 0, 0 },
				},
				ChestLowR = {
					pos = { 0.3825, 0, -0.336 },
					rot = { -90, 0, 0 },
				},
				ChestLowL = {
					pos = { -0.3825, 0, -0.336 },
					rot = { -90, 0, 0 },
				},
				BackR = {
					pos = { 0.34, 0.5, 0.3864 },
					rot = { 90, 0, 0 },
				},
				BackL = {
					pos = { -0.34, 0.5, 0.3864 },
					rot = { 90, 0, 0 },
				},
				FlankR = {
					pos = { 0.578, 0.1, 0.02 },
					rot = { 0, 0, -90 },
				},
				FlankL = {
					pos = { -0.578, 0.1, 0.02 },
					rot = { 0, 0, 90 },
				},
				ShoulderR = {
					pos = { 0.612, 0.9, 0 },
					rot = { 0, 0, 0 },
				},
				ShoulderL = {
					pos = { -0.612, 0.9, 0 },
					rot = { 0, 0, 0 },
				},
				HipR = {
					pos = { 0.5, -0.85, 0 },
					rot = { 0, 0, -90 },
				},
				HipL = {
					pos = { -0.5, -0.85, 0 },
					rot = { 0, 0, 90 },
				},
			},
			space = "torso",
			tags = { "thin", "bone" },
			variants = {
				Open = "EmaciatedTorsoOpen",
			},
		},
		EmaciatedTorsoOpen = {
			grade = "Grade4",
			hidden = True,
			layout = {
				neck = { 0, 1, -0.03 },
				shoulder = { 0.85, 0.6, 0 },
				hip = { 0.9, -1, 0 },
				tailRoot = { 0, -0.8, 0.35 },
				legExtra = 0.1,
			},
			pieces = {
				{
					name = "EmaciatedTorsoOpen_Bone",
					offset = { -0.0057, 0.1901, -0.3473 },
					role = "Bone",
					size = { 0.6315, 0.3092, 0.1173 },
					tris = 387,
				},
				{
					name = "EmaciatedTorsoOpen_Skin",
					offset = { 0.0019, 0.0339, 0.0173 },
					role = "Skin",
					size = { 1.724, 2.411, 0.8054 },
					tris = 3368,
				},
				{
					name = "EmaciatedTorsoOpen_SkinLight",
					offset = { 0.0069, 0.0434, -0.0046 },
					role = "SkinLight",
					size = { 1.409, 1.934, 0.8492 },
					tris = 3797,
				},
				{
					name = "EmaciatedTorsoOpen_Void",
					offset = { 0.001, 0.2354, -0.1636 },
					role = "Void",
					size = { 0.5811, 0.7906, 0.4312 },
					tris = 448,
				},
			},
			sided = False,
			slot = "Torso",
			sockets = {
				Chest = {
					pos = { 0, 0.3, -0.42 },
					rot = { -90, 0, 0 },
				},
				Belly = {
					pos = { 0, -0.35, -0.378 },
					rot = { -90, 0, 0 },
				},
				UpperBack = {
					pos = { 0, 0.6, 0.42 },
					rot = { 90, 0, 0 },
				},
				Back = {
					pos = { 0, 0.15, 0.4284 },
					rot = { 90, 0, 0 },
				},
				LowerBack = {
					pos = { 0, -0.4, 0.378 },
					rot = { 90, 0, 0 },
				},
				TailRoot = {
					pos = { 0, -0.8, 0.42 },
					rot = { 90, 0, 0 },
				},
				Neck = {
					pos = { 0, 1, 0.05 },
					rot = { 0, 0, 0 },
				},
				ChestR = {
					pos = { 0.272, 0.45, -0.399 },
					rot = { -90, 0, 0 },
				},
				ChestL = {
					pos = { -0.272, 0.45, -0.399 },
					rot = { -90, 0, 0 },
				},
				ChestLowR = {
					pos = { 0.3825, 0, -0.336 },
					rot = { -90, 0, 0 },
				},
				ChestLowL = {
					pos = { -0.3825, 0, -0.336 },
					rot = { -90, 0, 0 },
				},
				BackR = {
					pos = { 0.34, 0.5, 0.3864 },
					rot = { 90, 0, 0 },
				},
				BackL = {
					pos = { -0.34, 0.5, 0.3864 },
					rot = { 90, 0, 0 },
				},
				FlankR = {
					pos = { 0.578, 0.1, 0.02 },
					rot = { 0, 0, -90 },
				},
				FlankL = {
					pos = { -0.578, 0.1, 0.02 },
					rot = { 0, 0, 90 },
				},
				ShoulderR = {
					pos = { 0.612, 0.9, 0 },
					rot = { 0, 0, 0 },
				},
				ShoulderL = {
					pos = { -0.612, 0.9, 0 },
					rot = { 0, 0, 0 },
				},
				HipR = {
					pos = { 0.5, -0.85, 0 },
					rot = { 0, 0, -90 },
				},
				HipL = {
					pos = { -0.5, -0.85, 0 },
					rot = { 0, 0, 90 },
				},
			},
			space = "torso",
			tags = { "thin", "bone" },
		},
		ExtraEar = {
			grade = "Grade4",
			pieces = {
				{
					name = "ExtraEar_SkinDark",
					offset = { 0.0002, 0.1202, 0.0586 },
					role = "SkinDark",
					size = { 0.2797, 0.4391, 0.1094 },
					tris = 1216,
				},
				{
					name = "ExtraEar_SkinDeep",
					offset = { -0.0003, 0.1397, 0.0325 },
					role = "SkinDeep",
					size = { 0.1732, 0.2972, 0.0554 },
					tris = 284,
				},
			},
			sided = False,
			slot = "Disfigurements",
			slots = { "HeadGrowths", "Disfigurements", "TorsoGrowths" },
			socket = "TempleR",
			space = "surface",
			tags = { "growth" },
		},
		Eye = {
			grade = "Grade4",
			pieces = {
				{
					name = "Eye_Eye",
					offset = { -0.0015, 0.0148, -0.0203 },
					role = "Eye",
					size = { 0.223, 0.2453, 0.1857 },
					tris = 165,
				},
				{
					name = "Eye_Pupil",
					offset = { -0.0082, 0.1238, 0.0059 },
					role = "Pupil",
					size = { 0.0538, 0.0273, 0.1333 },
					tris = 29,
				},
				{
					name = "Eye_Skin",
					offset = { -0, -0.0277, 0.0001 },
					role = "Skin",
					size = { 0.4568, 0.1603, 0.4208 },
					tris = 851,
				},
				{
					name = "Eye_SkinDark",
					offset = { -0.0004, 0.0664, 0.0003 },
					role = "SkinDark",
					size = { 0.3517, 0.1007, 0.3526 },
					tris = 353,
				},
			},
			sided = False,
			slot = "Eyes",
			slots = { "Eyes", "Disfigurements" },
			socket = "Face",
			space = "surface",
			tags = { "eye" },
		},
		EyeCluster = {
			count = 5,
			grade = "Grade3",
			pieces = {
				{
					name = "EyeCluster_Eye",
					offset = { -0.0495, 0.0709, -0.0043 },
					role = "Eye",
					size = { 0.487, 0.054, 0.4804 },
					tris = 293,
				},
				{
					name = "EyeCluster_Pupil",
					offset = { -0.0107, 0.0781, -0.0435 },
					role = "Pupil",
					size = { 0.2545, 0.0396, 0.3407 },
					tris = 31,
				},
				{
					name = "EyeCluster_Skin",
					offset = { 0.0003, -0.0563, 0.0004 },
					role = "Skin",
					size = { 0.8393, 0.2477, 0.7597 },
					tris = 2513,
				},
				{
					name = "EyeCluster_SkinDark",
					offset = { -0.0543, 0.0424, -0.0149 },
					role = "SkinDark",
					size = { 0.5372, 0.0454, 0.5301 },
					tris = 161,
				},
			},
			sided = False,
			slot = "Eyes",
			slots = { "Eyes", "Disfigurements" },
			socket = "Face",
			space = "surface",
			tags = { "eye" },
		},
		FacelessHead = {
			defaults = {
				Eyes = {  },
				Mouths = {  },
			},
			grade = "Grade4",
			pieces = {
				{
					name = "FacelessHead_Skin",
					offset = { 0, 0.0991, -0.0223 },
					role = "Skin",
					size = { 1.197, 1.628, 1.364 },
					tris = 3937,
				},
				{
					name = "FacelessHead_SkinDark",
					offset = { 0.0025, 0.0717, -0.5668 },
					role = "SkinDark",
					size = { 0.0556, 1.146, 0.2651 },
					tris = 390,
				},
				{
					name = "FacelessHead_SkinLight",
					offset = { -0.004, -0.0496, -0.5232 },
					role = "SkinLight",
					size = { 1.026, 0.9358, 0.3534 },
					tris = 671,
				},
			},
			sided = False,
			slot = "Head",
			sockets = {
				Crown = {
					pos = { 0, 0.92, 0 },
					rot = { 0, 0, 0 },
				},
				Brow = {
					pos = { 0, 0.45, -0.58 },
					rot = { -60, 0, 0 },
				},
				Face = {
					pos = { 0, 0.05, -0.66 },
					rot = { -90, 0, 0 },
				},
				Mouth = {
					pos = { 0, -0.25, -0.62 },
					rot = { -90, 0, 0 },
				},
				Jaw = {
					pos = { 0, -0.62, -0.15 },
					rot = { 180, 0, 0 },
				},
				BackOfHead = {
					pos = { 0, 0.3, 0.66 },
					rot = { 90, 0, 0 },
				},
				TopR = {
					pos = { 0.33, 0.78, 0 },
					rot = { 0, 0, -30 },
				},
				TopL = {
					pos = { -0.33, 0.78, 0 },
					rot = { 0, 0, 30 },
				},
				EyeR = {
					pos = { 0.25, 0.15, -0.62 },
					rot = { -90, 0, 0 },
				},
				EyeL = {
					pos = { -0.25, 0.15, -0.62 },
					rot = { -90, 0, 0 },
				},
				CheekR = {
					pos = { 0.45, -0.1, -0.42 },
					rot = { -90, 0, -45 },
				},
				CheekL = {
					pos = { -0.45, -0.1, -0.42 },
					rot = { -90, 0, 45 },
				},
				TempleR = {
					pos = { 0.58, 0.3, 0 },
					rot = { 0, 0, -90 },
				},
				TempleL = {
					pos = { -0.58, 0.3, 0 },
					rot = { 0, 0, 90 },
				},
				EarR = {
					pos = { 0.6, 0.05, 0.05 },
					rot = { 0, 0, -90 },
				},
				EarL = {
					pos = { -0.6, 0.05, 0.05 },
					rot = { 0, 0, 90 },
				},
			},
			space = "head",
			tags = { "faceless" },
		},
		Fist = {
			grade = "Grade4",
			pieces = {
				{
					name = "Fist_Claw",
					offset = { -0.2404, -0.4334, -0.082 },
					role = "Claw",
					size = { 0.0681, 0.1154, 0.4648 },
					tris = 71,
				},
				{
					name = "Fist_Skin",
					offset = { 0.0077, -0.2809, -0.1245 },
					role = "Skin",
					size = { 0.6161, 0.7174, 0.747 },
					tris = 3927,
				},
			},
			sided = True,
			slot = "Hands",
			space = "hand",
			tags = { "hand", "reference" },
		},
		Foot = {
			grade = "Grade4",
			pieces = {
				{
					name = "Foot_Skin",
					offset = { -0.0004, 0.1277, -0.1457 },
					role = "Skin",
					size = { 0.3997, 0.2692, 0.8306 },
					tris = 2498,
				},
			},
			sided = True,
			slot = "Feet",
			space = "foot",
			tags = { "foot" },
		},
		GiantEye = {
			grade = "Grade3",
			pieces = {
				{
					name = "GiantEye_Eye",
					offset = { -0.0003, 0.0176, -0.0419 },
					role = "Eye",
					size = { 0.7106, 0.7207, 0.6234 },
					tris = 380,
				},
				{
					name = "GiantEye_Glow",
					offset = { 0.0043, 0.3632, 0.0093 },
					role = "Glow",
					size = { 0.4693, 0.113, 0.4462 },
					tris = 159,
				},
				{
					name = "GiantEye_Pupil",
					offset = { 0.0095, 0.4112, 0.0001 },
					role = "Pupil",
					size = { 0.1225, 0.0523, 0.3774 },
					tris = 58,
				},
				{
					name = "GiantEye_Skin",
					offset = { 0.0003, -0.0539, -0.0003 },
					role = "Skin",
					size = { 1.442, 0.4578, 1.331 },
					tris = 1403,
				},
				{
					name = "GiantEye_SkinDark",
					offset = { 0.0006, 0.2212, 0.0008 },
					role = "SkinDark",
					size = { 1.058, 0.2352, 1.069 },
					tris = 500,
				},
			},
			sided = False,
			slot = "Eyes",
			slots = { "Eyes", "Disfigurements" },
			socket = "Face",
			space = "surface",
			tags = { "eye" },
		},
		GlowPoint = {
			grade = "Grade4",
			hidden = True,
			pieces = {
				{
					name = "GlowPoint_Glow",
					offset = { -0.0004, -0.0001, 0.0003 },
					role = "Glow",
					size = { 0.141, 0.14, 0.1401 },
					tris = 298,
				},
			},
			sided = False,
			slot = "Eyes",
			slots = { "Eyes" },
			socket = "Face",
			space = "surface",
			tags = { "eye" },
		},
		GrinMouth = {
			grade = "Grade3",
			pieces = {
				{
					name = "GrinMouth_Skin",
					offset = { 0.0003, -0.0384, 0.0302 },
					role = "Skin",
					size = { 1.132, 0.2633, 0.5992 },
					tris = 2649,
				},
				{
					name = "GrinMouth_SkinDark",
					offset = { 0.0013, 0.0362, 0.0951 },
					role = "SkinDark",
					size = { 0.9565, 0.1242, 0.3895 },
					tris = 1263,
				},
				{
					name = "GrinMouth_Teeth",
					offset = { 0.0004, 0.055, 0.1403 },
					role = "Teeth",
					size = { 0.8195, 0.043, 0.0971 },
					tris = 86,
				},
			},
			sided = False,
			slot = "Mouths",
			slots = { "Mouths", "Disfigurements" },
			socket = "Mouth",
			space = "surface",
			tags = { "mouth", "teeth" },
		},
		HoofFoot = {
			grade = "Grade3",
			pieces = {
				{
					name = "HoofFoot_Claw",
					offset = { -0.0002, 0.1898, -0.0457 },
					role = "Claw",
					size = { 0.4405, 0.3924, 0.4455 },
					tris = 1787,
				},
				{
					name = "HoofFoot_Skin",
					offset = { -0.0036, 0.3397, 0.0317 },
					role = "Skin",
					size = { 0.3198, 0.1847, 0.2907 },
					tris = 443,
				},
				{
					name = "HoofFoot_Void",
					offset = { -0.0275, 0.101, -0.1122 },
					role = "Void",
					size = { 0.2765, 0.2147, 0.3052 },
					tris = 268,
				},
			},
			sided = True,
			slot = "Feet",
			space = "foot",
			tags = { "foot", "hoof" },
		},
		HumanCurseHead = {
			defaults = {
				Eyes = {
					{
						id = "Eye",
						socket = "EyeR",
					},
					{
						id = "Eye",
						socket = "EyeL",
					},
				},
				Mouths = {  },
			},
			grade = "Grade4",
			pieces = {
				{
					name = "HumanCurseHead_Skin",
					offset = { -0.0025, 0.0663, -0.0242 },
					role = "Skin",
					size = { 1.253, 1.553, 1.474 },
					tris = 5749,
				},
				{
					name = "HumanCurseHead_SkinDark",
					offset = { 0.0008, 0.0373, 0.0557 },
					role = "SkinDark",
					size = { 1.319, 0.3908, 0.2788 },
					tris = 414,
				},
				{
					name = "HumanCurseHead_SkinDeep",
					offset = { -0.0028, -0.0358, -0.5681 },
					role = "SkinDeep",
					size = { 0.7063, 0.551, 0.173 },
					tris = 344,
				},
				{
					name = "HumanCurseHead_SkinLight",
					offset = { 0.0156, 0.2835, -0.1536 },
					role = "SkinLight",
					size = { 0.9909, 1.016, 0.917 },
					tris = 491,
				},
			},
			sided = False,
			slot = "Head",
			sockets = {
				Crown = {
					pos = { 0, 0.85, 0.05 },
					rot = { 0, 0, 0 },
				},
				Brow = {
					pos = { 0, 0.4, -0.58 },
					rot = { -60, 0, 0 },
				},
				Face = {
					pos = { 0, 0.05, -0.68 },
					rot = { -90, 0, 0 },
				},
				Mouth = {
					pos = { 0, -0.26, -0.64 },
					rot = { -90, 0, 0 },
				},
				Jaw = {
					pos = { 0, -0.62, -0.25 },
					rot = { 180, 0, 0 },
				},
				BackOfHead = {
					pos = { 0, 0.25, 0.7 },
					rot = { 90, 0, 0 },
				},
				TopR = {
					pos = { 0.35, 0.72, 0 },
					rot = { 0, 0, -30 },
				},
				TopL = {
					pos = { -0.35, 0.72, 0 },
					rot = { 0, 0, 30 },
				},
				EyeR = {
					pos = { 0.24, 0.1, -0.52 },
					rot = { -90, 0, 0 },
				},
				EyeL = {
					pos = { -0.24, 0.1, -0.52 },
					rot = { -90, 0, 0 },
				},
				CheekR = {
					pos = { 0.45, -0.1, -0.42 },
					rot = { -90, 0, -45 },
				},
				CheekL = {
					pos = { -0.45, -0.1, -0.42 },
					rot = { -90, 0, 45 },
				},
				TempleR = {
					pos = { 0.6, 0.3, -0.05 },
					rot = { 0, 0, -90 },
				},
				TempleL = {
					pos = { -0.6, 0.3, -0.05 },
					rot = { 0, 0, 90 },
				},
				EarR = {
					pos = { 0.62, 0.02, 0.05 },
					rot = { 0, 0, -90 },
				},
				EarL = {
					pos = { -0.62, 0.02, 0.05 },
					rot = { 0, 0, 90 },
				},
			},
			space = "head",
			tags = { "humanoid" },
		},
		HuskArm = {
			grade = "Grade3",
			pieces = {
				{
					name = "HuskArm_Flesh",
					offset = { -0.4739, -0.7264, -0.0796 },
					role = "Flesh",
					size = { 0.2817, 0.9355, 0.5988 },
					tris = 889,
				},
				{
					name = "HuskArm_Skin",
					offset = { -0.406, -0.2305, 0.0693 },
					role = "Skin",
					size = { 1.044, 2.191, 0.9884 },
					tris = 6111,
				},
			},
			pivot = { -0.5, 0.5, 0 },
			sided = True,
			slot = "Arms",
			sockets = {
				Shoulder = {
					pos = { -0.47, 0.7, 0.05 },
					rot = { 0, 0, 0 },
				},
				UpperArm = {
					pos = { 0.02, 0.025, 0 },
					rot = { 0, 0, -90 },
				},
				Elbow = {
					pos = { -0.27, -0.35, 0.405 },
					rot = { 90, 0, 0 },
				},
				Forearm = {
					pos = { 0.065, -0.725, -0.06 },
					rot = { 0, 0, -90 },
				},
				Hand = {
					pos = { -0.25, -1.15, -0.2 },
					rot = { 0, 0, 0 },
				},
				Palm = {
					pos = { -0.4, -1.4, -0.2 },
					rot = { 0, 0, 90 },
				},
			},
			space = "arm",
			tags = { "arm", "reference" },
		},
		HuskHead = {
			defaults = {
				Eyes = {  },
				Mouths = {  },
			},
			grade = "Grade2",
			pieces = {
				{
					name = "HuskHead_Claw",
					offset = { -0.0298, 0.5003, 0.1474 },
					role = "Claw",
					size = { 0.9185, 1.212, 1.075 },
					tris = 418,
				},
				{
					name = "HuskHead_Eye",
					offset = { -0.3788, -0.0049, -0.2809 },
					role = "Eye",
					size = { 0.1352, 0.1342, 0.1381 },
					tris = 138,
				},
				{
					name = "HuskHead_Skin",
					offset = { -0.0021, -0.0264, 0.1903 },
					role = "Skin",
					size = { 1.251, 2.298, 1.666 },
					tris = 9442,
				},
			},
			sided = False,
			slot = "Head",
			sockets = {
				Crown = {
					pos = { 0, 0.95, 0.35 },
					rot = { 0, 0, 0 },
				},
				Brow = {
					pos = { 0, 0.22, -0.45 },
					rot = { -60, 0, 0 },
				},
				Face = {
					pos = { 0, -0.12, -0.62 },
					rot = { -90, 0, 0 },
				},
				Mouth = {
					pos = { 0, -0.45, -0.52 },
					rot = { -90, 0, 0 },
				},
				Jaw = {
					pos = { 0, -0.62, -0.3 },
					rot = { 180, 0, 0 },
				},
				BackOfHead = {
					pos = { 0, 0.6, 0.85 },
					rot = { 90, 0, 0 },
				},
				TopR = {
					pos = { 0.42, 0.82, 0.2 },
					rot = { 0, 0, -30 },
				},
				TopL = {
					pos = { -0.42, 0.82, 0.2 },
					rot = { 0, 0, 30 },
				},
				EyeR = {
					pos = { 0.4, 0, -0.3 },
					rot = { -90, 0, -50 },
				},
				EyeL = {
					pos = { -0.4, 0, -0.3 },
					rot = { -90, 0, 50 },
				},
				CheekR = {
					pos = { 0.42, -0.15, -0.38 },
					rot = { -90, 0, -45 },
				},
				CheekL = {
					pos = { -0.42, -0.15, -0.38 },
					rot = { -90, 0, 45 },
				},
				TempleR = {
					pos = { 0.58, 0.25, 0.02 },
					rot = { 0, 0, -90 },
				},
				TempleL = {
					pos = { -0.58, 0.25, 0.02 },
					rot = { 0, 0, 90 },
				},
				EarR = {
					pos = { 0.58, 0, 0.1 },
					rot = { 0, 0, -90 },
				},
				EarL = {
					pos = { -0.58, 0, 0.1 },
					rot = { 0, 0, 90 },
				},
			},
			space = "head",
			tags = { "reference", "tentacle" },
		},
		HuskLeg = {
			grade = "Grade3",
			pieces = {
				{
					name = "HuskLeg_Flesh",
					offset = { -0.2097, -0.1074, -0.2317 },
					role = "Flesh",
					size = { 0.4494, 1.846, 0.6586 },
					tris = 859,
				},
				{
					name = "HuskLeg_Skin",
					offset = { -0.0276, 0.0158, -0.0757 },
					role = "Skin",
					size = { 0.8775, 2.428, 0.9696 },
					tris = 5141,
				},
			},
			pivot = { 0.5, 1, 0 },
			sided = True,
			slot = "Legs",
			sockets = {
				Thigh = {
					pos = { -0.005, 0.31, -0.345 },
					rot = { -90, 0, 0 },
				},
				Knee = {
					pos = { 0.02, -0.15, -0.46 },
					rot = { -90, 0, 0 },
				},
				Shin = {
					pos = { 0.23, -0.61, -0.13 },
					rot = { 0, 0, -90 },
				},
				Foot = {
					pos = { 0.02, -1.35, -0.03 },
					rot = { 0, 0, 0 },
				},
			},
			space = "leg",
			span = 2.35,
			tags = { "leg", "reference" },
		},
		HuskTail = {
			grade = "Grade3",
			pieces = {
				{
					name = "HuskTail_Claw",
					offset = { -1.19, -1.775, 0.4099 },
					role = "Claw",
					size = { 0.1937, 0.3295, 0.2088 },
					tris = 184,
				},
				{
					name = "HuskTail_Skin",
					offset = { -0.4548, -0.8646, 0.3332 },
					role = "Skin",
					size = { 1.431, 2.247, 1.385 },
					tris = 3314,
				},
			},
			sided = False,
			slot = "Tails",
			socket = "TailRoot",
			space = "body",
			tags = { "tail", "reference" },
		},
		HuskTorso = {
			grade = "Grade3",
			layout = {
				neck = { 0, 0.6, -0.8 },
				shoulder = { 1.05, 0.55, -0.2 },
				hip = { 0.98, -1, 0.05 },
				tailRoot = { -0.2, -0.7, 0.55 },
				legExtra = 0.35,
			},
			pieces = {
				{
					name = "HuskTorso_Flesh",
					offset = { 0.0234, -0.1689, -0.546 },
					role = "Flesh",
					size = { 1.763, 2.086, 0.6805 },
					tris = 2142,
				},
				{
					name = "HuskTorso_Skin",
					offset = { 0.0016, 0.0801, 0.0412 },
					role = "Skin",
					size = { 2.467, 2.763, 1.888 },
					tris = 7035,
				},
				{
					name = "HuskTorso_Void",
					offset = { -0.0839, 0.0032, -0.5475 },
					role = "Void",
					size = { 0.9284, 1.323, 0.6152 },
					tris = 821,
				},
			},
			sided = False,
			slot = "Torso",
			sockets = {
				Chest = {
					pos = { 0, 0.05, -0.95 },
					rot = { -90, 0, 0 },
				},
				Belly = {
					pos = { 0, -0.5, -0.855 },
					rot = { -90, 0, 0 },
				},
				UpperBack = {
					pos = { 0, 0.6, 0.95 },
					rot = { 90, 0, 0 },
				},
				Back = {
					pos = { 0, 0.15, 0.969 },
					rot = { 90, 0, 0 },
				},
				LowerBack = {
					pos = { 0, -0.4, 0.855 },
					rot = { 90, 0, 0 },
				},
				TailRoot = {
					pos = { -0.2, -0.7, 0.55 },
					rot = { 90, 0, 0 },
				},
				Neck = {
					pos = { 0, 1.05, -0.3 },
					rot = { 0, 0, 0 },
				},
				ChestR = {
					pos = { 0.352, 0.2, -0.9025 },
					rot = { -90, 0, 0 },
				},
				ChestL = {
					pos = { -0.352, 0.2, -0.9025 },
					rot = { -90, 0, 0 },
				},
				ChestLowR = {
					pos = { 0.495, -0.15, -0.76 },
					rot = { -90, 0, 0 },
				},
				ChestLowL = {
					pos = { -0.495, -0.15, -0.76 },
					rot = { -90, 0, 0 },
				},
				BackR = {
					pos = { 0.44, 0.5, 0.874 },
					rot = { 90, 0, 0 },
				},
				BackL = {
					pos = { -0.44, 0.5, 0.874 },
					rot = { 90, 0, 0 },
				},
				FlankR = {
					pos = { 0.748, 0.1, 0.02 },
					rot = { 0, 0, -90 },
				},
				FlankL = {
					pos = { -0.748, 0.1, 0.02 },
					rot = { 0, 0, 90 },
				},
				ShoulderR = {
					pos = { 0.792, 1.05, 0 },
					rot = { 0, 0, 0 },
				},
				ShoulderL = {
					pos = { -0.792, 1.05, 0 },
					rot = { 0, 0, 0 },
				},
				HipR = {
					pos = { 0.72, -0.85, 0 },
					rot = { 0, 0, -90 },
				},
				HipL = {
					pos = { -0.72, -0.85, 0 },
					rot = { 0, 0, 90 },
				},
			},
			space = "torso",
			tags = { "hunched", "reference" },
		},
		MandibleHead = {
			defaults = {
				Eyes = {  },
				Mouths = {
					{
						id = "Mandibles",
						socket = "Mouth",
					},
				},
			},
			grade = "Grade3",
			pieces = {
				{
					name = "MandibleHead_Glow",
					offset = { 0.001, 0.2099, -0.1592 },
					role = "Glow",
					size = { 1.191, 0.2753, 0.1433 },
					tris = 282,
				},
				{
					name = "MandibleHead_Skin",
					offset = { -0.0011, 0.4153, -0.265 },
					role = "Skin",
					size = { 0.9607, 0.5117, 1.012 },
					tris = 1069,
				},
				{
					name = "MandibleHead_SkinDark",
					offset = { 0.0004, 0.1027, 0.0512 },
					role = "SkinDark",
					size = { 0.9979, 1.502, 1.926 },
					tris = 4437,
				},
				{
					name = "MandibleHead_Void",
					offset = { 0.0006, 0.219, -0.2589 },
					role = "Void",
					size = { 1.19, 0.5047, 0.5256 },
					tris = 1210,
				},
			},
			sided = False,
			slot = "Head",
			sockets = {
				Crown = {
					pos = { 0, 0.72, 0.1 },
					rot = { 0, 0, 0 },
				},
				Brow = {
					pos = { 0, 0.45, -0.52 },
					rot = { -60, 0, 0 },
				},
				Face = {
					pos = { 0, 0.1, -0.78 },
					rot = { -90, 0, 0 },
				},
				Mouth = {
					pos = { 0, -0.35, -0.72 },
					rot = { -90, 0, 0 },
				},
				Jaw = {
					pos = { 0, -0.5, -0.4 },
					rot = { 180, 0, 0 },
				},
				BackOfHead = {
					pos = { 0, 0.35, 0.85 },
					rot = { 90, 0, 0 },
				},
				TopR = {
					pos = { 0.3, 0.62, 0 },
					rot = { 0, 0, -30 },
				},
				TopL = {
					pos = { -0.3, 0.62, 0 },
					rot = { 0, 0, 30 },
				},
				EyeR = {
					pos = { 0.42, 0.25, -0.3 },
					rot = { -90, 0, -60 },
				},
				EyeL = {
					pos = { -0.42, 0.25, -0.3 },
					rot = { -90, 0, 60 },
				},
				CheekR = {
					pos = { 0.45, -0.1, -0.45 },
					rot = { -90, 0, -45 },
				},
				CheekL = {
					pos = { -0.45, -0.1, -0.45 },
					rot = { -90, 0, 45 },
				},
				TempleR = {
					pos = { 0.5, 0.35, 0.1 },
					rot = { 0, 0, -90 },
				},
				TempleL = {
					pos = { -0.5, 0.35, 0.1 },
					rot = { 0, 0, 90 },
				},
				EarR = {
					pos = { 0.5, 0.2, 0.25 },
					rot = { 0, 0, -90 },
				},
				EarL = {
					pos = { -0.5, 0.2, 0.25 },
					rot = { 0, 0, 90 },
				},
			},
			space = "head",
			tags = { "insect" },
		},
		Mandibles = {
			grade = "Grade3",
			pieces = {
				{
					name = "Mandibles_Claw",
					offset = { -0.0004, 0.2906, -0.141 },
					role = "Claw",
					size = { 0.8091, 0.7085, 0.4482 },
					tris = 2087,
				},
				{
					name = "Mandibles_SkinDark",
					offset = { 0.0044, 0.0021, 0.0005 },
					role = "SkinDark",
					size = { 0.3439, 0.1647, 0.2396 },
					tris = 361,
				},
				{
					name = "Mandibles_Teeth",
					offset = { 0.0011, 0.3654, -0.1611 },
					role = "Teeth",
					size = { 0.5547, 0.1102, 0.0718 },
					tris = 50,
				},
			},
			sided = False,
			slot = "Mouths",
			slots = { "Mouths", "Disfigurements" },
			socket = "Mouth",
			space = "surface",
			tags = { "mouth", "insect" },
		},
		MassiveHorn = {
			grade = "Grade2",
			pieces = {
				{
					name = "MassiveHorn_Bone",
					offset = { 0.9947, 0.7025, 0.1195 },
					role = "Bone",
					size = { 1.812, 0.805, 0.6365 },
					tris = 1075,
				},
				{
					name = "MassiveHorn_BoneDark",
					offset = { 0.2195, 0.3203, 0.0028 },
					role = "BoneDark",
					size = { 1.072, 1.298, 0.6329 },
					tris = 707,
				},
				{
					name = "MassiveHorn_Claw",
					offset = { 1.803, 0.9533, 0.3782 },
					role = "Claw",
					size = { 0.3702, 0.1578, 0.1509 },
					tris = 98,
				},
				{
					name = "MassiveHorn_Skin",
					offset = { -0.0001, -0.0791, -0.0003 },
					role = "Skin",
					size = { 0.8394, 0.3877, 0.8388 },
					tris = 618,
				},
			},
			sided = True,
			slot = "Horns",
			socket = "Crown",
			space = "surface",
			tags = { "horn", "bone" },
		},
		MassiveLeg = {
			grade = "Grade3",
			pieces = {
				{
					name = "MassiveLeg_Skin",
					offset = { 0.009, 0.0899, 0.014 },
					role = "Skin",
					size = { 1.023, 2.281, 1.06 },
					tris = 5000,
				},
			},
			pivot = { 0.5, 1, 0 },
			sided = True,
			slot = "Legs",
			sockets = {
				Thigh = {
					pos = { 0.02, 0.325, -0.4312 },
					rot = { -90, 0, 0 },
				},
				Knee = {
					pos = { 0.02, -0.1, -0.4075 },
					rot = { -90, 0, 0 },
				},
				Shin = {
					pos = { 0.2875, -0.475, -0.045 },
					rot = { 0, 0, -90 },
				},
				Foot = {
					pos = { 0.02, -1, 0 },
					rot = { 0, 0, 0 },
				},
			},
			space = "leg",
			span = 2,
			tags = { "leg" },
		},
		MassiveTorso = {
			grade = "Grade1",
			hidden = False,
			layout = {
				neck = { 0, 0.85, -0.35 },
				shoulder = { 1.45, 0.45, -0.05 },
				hip = { 1.15, -1, 0 },
				tailRoot = { 0, -0.8, 0.62 },
				legExtra = 0.15,
			},
			pieces = {
				{
					name = "MassiveTorso_Skin",
					offset = { 0.0028, -0.0275, -0.0086 },
					role = "Skin",
					size = { 3.259, 2.451, 1.648 },
					tris = 7253,
				},
				{
					name = "MassiveTorso_SkinLight",
					offset = { 0.0087, 0.6529, 0.0332 },
					role = "SkinLight",
					size = { 1.883, 1.315, 1.728 },
					tris = 1747,
				},
			},
			sided = False,
			slot = "Torso",
			sockets = {
				Chest = {
					pos = { 0, 0.3, -0.82 },
					rot = { -90, 0, 0 },
				},
				Belly = {
					pos = { 0, -0.35, -0.738 },
					rot = { -90, 0, 0 },
				},
				UpperBack = {
					pos = { 0, 0.6, 0.9 },
					rot = { 90, 0, 0 },
				},
				Back = {
					pos = { 0, 0.15, 0.918 },
					rot = { 90, 0, 0 },
				},
				LowerBack = {
					pos = { 0, -0.4, 0.81 },
					rot = { 90, 0, 0 },
				},
				TailRoot = {
					pos = { 0, -0.8, 0.62 },
					rot = { 90, 0, 0 },
				},
				Neck = {
					pos = { 0, 1.1, -0.2 },
					rot = { 0, 0, 0 },
				},
				ChestR = {
					pos = { 0.464, 0.45, -0.779 },
					rot = { -90, 0, 0 },
				},
				ChestL = {
					pos = { -0.464, 0.45, -0.779 },
					rot = { -90, 0, 0 },
				},
				ChestLowR = {
					pos = { 0.6525, 0, -0.656 },
					rot = { -90, 0, 0 },
				},
				ChestLowL = {
					pos = { -0.6525, 0, -0.656 },
					rot = { -90, 0, 0 },
				},
				BackR = {
					pos = { 0.58, 0.5, 0.828 },
					rot = { 90, 0, 0 },
				},
				BackL = {
					pos = { -0.58, 0.5, 0.828 },
					rot = { 90, 0, 0 },
				},
				FlankR = {
					pos = { 0.986, 0.1, 0.02 },
					rot = { 0, 0, -90 },
				},
				FlankL = {
					pos = { -0.986, 0.1, 0.02 },
					rot = { 0, 0, 90 },
				},
				ShoulderR = {
					pos = { 1.044, 1.05, 0 },
					rot = { 0, 0, 0 },
				},
				ShoulderL = {
					pos = { -1.044, 1.05, 0 },
					rot = { 0, 0, 0 },
				},
				HipR = {
					pos = { 0.8, -0.85, 0 },
					rot = { 0, 0, -90 },
				},
				HipL = {
					pos = { -0.8, -0.85, 0 },
					rot = { 0, 0, 90 },
				},
			},
			space = "torso",
			tags = { "massive" },
			variants = {
				Open = "MassiveTorsoOpen",
			},
		},
		MassiveTorsoOpen = {
			grade = "Grade1",
			hidden = True,
			layout = {
				neck = { 0, 0.85, -0.35 },
				shoulder = { 1.45, 0.45, -0.05 },
				hip = { 1.15, -1, 0 },
				tailRoot = { 0, -0.8, 0.62 },
				legExtra = 0.15,
			},
			pieces = {
				{
					name = "MassiveTorsoOpen_Bone",
					offset = { 0.0053, 0.1116, -0.7138 },
					role = "Bone",
					size = { 0.9289, 0.3793, 0.122 },
					tris = 363,
				},
				{
					name = "MassiveTorsoOpen_Skin",
					offset = { 0.0028, -0.0275, 0.0097 },
					role = "Skin",
					size = { 3.259, 2.451, 1.615 },
					tris = 6235,
				},
				{
					name = "MassiveTorsoOpen_SkinLight",
					offset = { 0.0087, 0.6614, 0.0339 },
					role = "SkinLight",
					size = { 1.883, 1.299, 1.727 },
					tris = 1485,
				},
				{
					name = "MassiveTorsoOpen_Void",
					offset = { -0.0003, 0.0861, -0.5198 },
					role = "Void",
					size = { 0.9596, 1.129, 0.6167 },
					tris = 917,
				},
			},
			sided = False,
			slot = "Torso",
			sockets = {
				Chest = {
					pos = { 0, 0.3, -0.82 },
					rot = { -90, 0, 0 },
				},
				Belly = {
					pos = { 0, -0.35, -0.738 },
					rot = { -90, 0, 0 },
				},
				UpperBack = {
					pos = { 0, 0.6, 0.9 },
					rot = { 90, 0, 0 },
				},
				Back = {
					pos = { 0, 0.15, 0.918 },
					rot = { 90, 0, 0 },
				},
				LowerBack = {
					pos = { 0, -0.4, 0.81 },
					rot = { 90, 0, 0 },
				},
				TailRoot = {
					pos = { 0, -0.8, 0.62 },
					rot = { 90, 0, 0 },
				},
				Neck = {
					pos = { 0, 1.1, -0.2 },
					rot = { 0, 0, 0 },
				},
				ChestR = {
					pos = { 0.464, 0.45, -0.779 },
					rot = { -90, 0, 0 },
				},
				ChestL = {
					pos = { -0.464, 0.45, -0.779 },
					rot = { -90, 0, 0 },
				},
				ChestLowR = {
					pos = { 0.6525, 0, -0.656 },
					rot = { -90, 0, 0 },
				},
				ChestLowL = {
					pos = { -0.6525, 0, -0.656 },
					rot = { -90, 0, 0 },
				},
				BackR = {
					pos = { 0.58, 0.5, 0.828 },
					rot = { 90, 0, 0 },
				},
				BackL = {
					pos = { -0.58, 0.5, 0.828 },
					rot = { 90, 0, 0 },
				},
				FlankR = {
					pos = { 0.986, 0.1, 0.02 },
					rot = { 0, 0, -90 },
				},
				FlankL = {
					pos = { -0.986, 0.1, 0.02 },
					rot = { 0, 0, 90 },
				},
				ShoulderR = {
					pos = { 1.044, 1.05, 0 },
					rot = { 0, 0, 0 },
				},
				ShoulderL = {
					pos = { -1.044, 1.05, 0 },
					rot = { 0, 0, 0 },
				},
				HipR = {
					pos = { 0.8, -0.85, 0 },
					rot = { 0, 0, -90 },
				},
				HipL = {
					pos = { -0.8, -0.85, 0 },
					rot = { 0, 0, 90 },
				},
			},
			space = "torso",
			tags = { "massive" },
		},
		Maw = {
			grade = "Grade2",
			pieces = {
				{
					name = "Maw_Skin",
					offset = { 0.0002, -0.0086, -0.0019 },
					role = "Skin",
					size = { 0.9352, 0.2632, 1.128 },
					tris = 1965,
				},
				{
					name = "Maw_SkinDark",
					offset = { 0.0032, 0.0225, -0.0001 },
					role = "SkinDark",
					size = { 0.9235, 0.2958, 1.249 },
					tris = 2393,
				},
				{
					name = "Maw_Teeth",
					offset = { -0.0021, 0.1203, 0.0129 },
					role = "Teeth",
					size = { 0.471, 0.039, 0.681 },
					tris = 642,
				},
			},
			sided = False,
			slot = "Mouths",
			slots = { "Mouths", "Disfigurements" },
			socket = "Chest",
			space = "surface",
			tags = { "mouth", "teeth" },
		},
		MuscularArm = {
			grade = "Grade4",
			pieces = {
				{
					name = "MuscularArm_Skin",
					offset = { -0.4032, -0.1814, -0.0005 },
					role = "Skin",
					size = { 0.9472, 2.159, 0.9886 },
					tris = 4687,
				},
				{
					name = "MuscularArm_SkinDark",
					offset = { -0.237, -0.815, -0.2793 },
					role = "SkinDark",
					size = { 0.115, 0.2005, 0.0316 },
					tris = 24,
				},
				{
					name = "MuscularArm_SkinLight",
					offset = { -0.3405, -0.0253, -0.2586 },
					role = "SkinLight",
					size = { 0.5961, 0.4842, 0.2919 },
					tris = 289,
				},
			},
			pivot = { -0.5, 0.5, 0 },
			sided = True,
			slot = "Arms",
			sockets = {
				Shoulder = {
					pos = { -0.42, 0.72, 0 },
					rot = { 0, 0, 0 },
				},
				UpperArm = {
					pos = { 0.03611, 0.035, 0 },
					rot = { 0, 0, -90 },
				},
				Elbow = {
					pos = { -0.33, -0.35, 0.4026 },
					rot = { 90, 0, 0 },
				},
				Forearm = {
					pos = { 0.02759, -0.7, -0.01 },
					rot = { 0, 0, -90 },
				},
				Hand = {
					pos = { -0.3, -1.1, -0.08 },
					rot = { 0, 0, 0 },
				},
				Palm = {
					pos = { -0.45, -1.35, -0.08 },
					rot = { 0, 0, 90 },
				},
			},
			space = "arm",
			tags = { "arm" },
		},
		MuscularTorso = {
			grade = "Grade4",
			hidden = False,
			layout = {
				neck = { 0, 0.95, -0.08 },
				shoulder = { 1.2, 0.55, 0 },
				hip = { 1.05, -1, 0 },
				tailRoot = { 0, -0.8, 0.5 },
				legExtra = 0,
			},
			pieces = {
				{
					name = "MuscularTorso_Skin",
					offset = { -0.0001, 0.0646, 0.005 },
					role = "Skin",
					size = { 2.691, 2.597, 1.219 },
					tris = 6996,
				},
				{
					name = "MuscularTorso_SkinLight",
					offset = { -0.0123, 0.1021, -0.4767 },
					role = "SkinLight",
					size = { 1.73, 1.313, 0.3261 },
					tris = 1004,
				},
			},
			sided = False,
			slot = "Torso",
			sockets = {
				Chest = {
					pos = { 0, 0.3, -0.62 },
					rot = { -90, 0, 0 },
				},
				Belly = {
					pos = { 0, -0.35, -0.558 },
					rot = { -90, 0, 0 },
				},
				UpperBack = {
					pos = { 0, 0.6, 0.62 },
					rot = { 90, 0, 0 },
				},
				Back = {
					pos = { 0, 0.15, 0.6324 },
					rot = { 90, 0, 0 },
				},
				LowerBack = {
					pos = { 0, -0.4, 0.558 },
					rot = { 90, 0, 0 },
				},
				TailRoot = {
					pos = { 0, -0.8, 0.42 },
					rot = { 90, 0, 0 },
				},
				Neck = {
					pos = { 0, 1, 0.05 },
					rot = { 0, 0, 0 },
				},
				ChestR = {
					pos = { 0.384, 0.45, -0.589 },
					rot = { -90, 0, 0 },
				},
				ChestL = {
					pos = { -0.384, 0.45, -0.589 },
					rot = { -90, 0, 0 },
				},
				ChestLowR = {
					pos = { 0.54, 0, -0.496 },
					rot = { -90, 0, 0 },
				},
				ChestLowL = {
					pos = { -0.54, 0, -0.496 },
					rot = { -90, 0, 0 },
				},
				BackR = {
					pos = { 0.48, 0.5, 0.5704 },
					rot = { 90, 0, 0 },
				},
				BackL = {
					pos = { -0.48, 0.5, 0.5704 },
					rot = { 90, 0, 0 },
				},
				FlankR = {
					pos = { 0.816, 0.1, 0.02 },
					rot = { 0, 0, -90 },
				},
				FlankL = {
					pos = { -0.816, 0.1, 0.02 },
					rot = { 0, 0, 90 },
				},
				ShoulderR = {
					pos = { 0.864, 1.05, 0 },
					rot = { 0, 0, 0 },
				},
				ShoulderL = {
					pos = { -0.864, 1.05, 0 },
					rot = { 0, 0, 0 },
				},
				HipR = {
					pos = { 0.62, -0.85, 0 },
					rot = { 0, 0, -90 },
				},
				HipL = {
					pos = { -0.62, -0.85, 0 },
					rot = { 0, 0, 90 },
				},
			},
			space = "torso",
			tags = { "muscle" },
			variants = {
				Open = "MuscularTorsoOpen",
			},
		},
		MuscularTorsoOpen = {
			grade = "Grade4",
			hidden = True,
			layout = {
				neck = { 0, 0.95, -0.08 },
				shoulder = { 1.2, 0.55, 0 },
				hip = { 1.05, -1, 0 },
				tailRoot = { 0, -0.8, 0.5 },
				legExtra = 0,
			},
			pieces = {
				{
					name = "MuscularTorsoOpen_Bone",
					offset = { 0.0056, 0.15, -0.5551 },
					role = "Bone",
					size = { 0.7736, 0.3608, 0.1026 },
					tris = 385,
				},
				{
					name = "MuscularTorsoOpen_Skin",
					offset = { -0.0003, 0.0646, 0.0568 },
					role = "Skin",
					size = { 2.69, 2.597, 1.116 },
					tris = 6162,
				},
				{
					name = "MuscularTorsoOpen_SkinLight",
					offset = { 0.0027, 0.1025, -0.4803 },
					role = "SkinLight",
					size = { 1.721, 1.314, 0.3179 },
					tris = 790,
				},
				{
					name = "MuscularTorsoOpen_Void",
					offset = { 0.005, 0.1803, -0.3657 },
					role = "Void",
					size = { 0.797, 0.9774, 0.5363 },
					tris = 663,
				},
			},
			sided = False,
			slot = "Torso",
			sockets = {
				Chest = {
					pos = { 0, 0.3, -0.62 },
					rot = { -90, 0, 0 },
				},
				Belly = {
					pos = { 0, -0.35, -0.558 },
					rot = { -90, 0, 0 },
				},
				UpperBack = {
					pos = { 0, 0.6, 0.62 },
					rot = { 90, 0, 0 },
				},
				Back = {
					pos = { 0, 0.15, 0.6324 },
					rot = { 90, 0, 0 },
				},
				LowerBack = {
					pos = { 0, -0.4, 0.558 },
					rot = { 90, 0, 0 },
				},
				TailRoot = {
					pos = { 0, -0.8, 0.42 },
					rot = { 90, 0, 0 },
				},
				Neck = {
					pos = { 0, 1, 0.05 },
					rot = { 0, 0, 0 },
				},
				ChestR = {
					pos = { 0.384, 0.45, -0.589 },
					rot = { -90, 0, 0 },
				},
				ChestL = {
					pos = { -0.384, 0.45, -0.589 },
					rot = { -90, 0, 0 },
				},
				ChestLowR = {
					pos = { 0.54, 0, -0.496 },
					rot = { -90, 0, 0 },
				},
				ChestLowL = {
					pos = { -0.54, 0, -0.496 },
					rot = { -90, 0, 0 },
				},
				BackR = {
					pos = { 0.48, 0.5, 0.5704 },
					rot = { 90, 0, 0 },
				},
				BackL = {
					pos = { -0.48, 0.5, 0.5704 },
					rot = { 90, 0, 0 },
				},
				FlankR = {
					pos = { 0.816, 0.1, 0.02 },
					rot = { 0, 0, -90 },
				},
				FlankL = {
					pos = { -0.816, 0.1, 0.02 },
					rot = { 0, 0, 90 },
				},
				ShoulderR = {
					pos = { 0.864, 1.05, 0 },
					rot = { 0, 0, 0 },
				},
				ShoulderL = {
					pos = { -0.864, 1.05, 0 },
					rot = { 0, 0, 0 },
				},
				HipR = {
					pos = { 0.62, -0.85, 0 },
					rot = { 0, 0, -90 },
				},
				HipL = {
					pos = { -0.62, -0.85, 0 },
					rot = { 0, 0, 90 },
				},
			},
			space = "torso",
			tags = { "muscle" },
		},
		NormalArm = {
			grade = "Grade4",
			pieces = {
				{
					name = "NormalArm_Skin",
					offset = { -0.4016, -0.2047, -0.0021 },
					role = "Skin",
					size = { 0.7346, 2.008, 0.7693 },
					tris = 4998,
				},
			},
			pivot = { -0.5, 0.5, 0 },
			sided = True,
			slot = "Arms",
			sockets = {
				Shoulder = {
					pos = { -0.42, 0.72, 0 },
					rot = { 0, 0, 0 },
				},
				UpperArm = {
					pos = { -0.075, 0.035, 0 },
					rot = { 0, 0, -90 },
				},
				Elbow = {
					pos = { -0.33, -0.35, 0.31 },
					rot = { 90, 0, 0 },
				},
				Forearm = {
					pos = { -0.065, -0.7, -0.01 },
					rot = { 0, 0, -90 },
				},
				Hand = {
					pos = { -0.3, -1.1, -0.08 },
					rot = { 0, 0, 0 },
				},
				Palm = {
					pos = { -0.45, -1.35, -0.08 },
					rot = { 0, 0, 90 },
				},
			},
			space = "arm",
			tags = { "arm" },
		},
		NormalLeg = {
			grade = "Grade4",
			pieces = {
				{
					name = "NormalLeg_Skin",
					offset = { 0.0092, 0.0898, 0.0118 },
					role = "Skin",
					size = { 0.7365, 2.152, 0.7635 },
					tris = 5000,
				},
			},
			pivot = { 0.5, 1, 0 },
			sided = True,
			slot = "Legs",
			sockets = {
				Thigh = {
					pos = { 0.02, 0.325, -0.3 },
					rot = { -90, 0, 0 },
				},
				Knee = {
					pos = { 0.02, -0.1, -0.32 },
					rot = { -90, 0, 0 },
				},
				Shin = {
					pos = { 0.2, -0.475, -0.045 },
					rot = { 0, 0, -90 },
				},
				Foot = {
					pos = { 0.02, -1, 0 },
					rot = { 0, 0, 0 },
				},
			},
			space = "leg",
			span = 2,
			tags = { "leg" },
		},
		NormalTorso = {
			grade = "Grade4",
			hidden = False,
			layout = {
				neck = { 0, 1, -0.05 },
				shoulder = { 1, 0.55, 0 },
				hip = { 1, -1, 0 },
				tailRoot = { 0, -0.8, 0.42 },
				legExtra = 0,
			},
			pieces = {
				{
					name = "NormalTorso_Skin",
					offset = { -0.0002, 0.0444, 0.0251 },
					role = "Skin",
					size = { 2.119, 2.556, 1.039 },
					tris = 6390,
				},
				{
					name = "NormalTorso_SkinLight",
					offset = { -0.0039, 0.0753, -0.3694 },
					role = "SkinLight",
					size = { 1.349, 1.288, 0.2691 },
					tris = 608,
				},
			},
			sided = False,
			slot = "Torso",
			sockets = {
				Chest = {
					pos = { 0, 0.3, -0.5 },
					rot = { -90, 0, 0 },
				},
				Belly = {
					pos = { 0, -0.35, -0.45 },
					rot = { -90, 0, 0 },
				},
				UpperBack = {
					pos = { 0, 0.6, 0.5 },
					rot = { 90, 0, 0 },
				},
				Back = {
					pos = { 0, 0.15, 0.51 },
					rot = { 90, 0, 0 },
				},
				LowerBack = {
					pos = { 0, -0.4, 0.45 },
					rot = { 90, 0, 0 },
				},
				TailRoot = {
					pos = { 0, -0.8, 0.42 },
					rot = { 90, 0, 0 },
				},
				Neck = {
					pos = { 0, 1, 0.05 },
					rot = { 0, 0, 0 },
				},
				ChestR = {
					pos = { 0.32, 0.45, -0.475 },
					rot = { -90, 0, 0 },
				},
				ChestL = {
					pos = { -0.32, 0.45, -0.475 },
					rot = { -90, 0, 0 },
				},
				ChestLowR = {
					pos = { 0.45, 0, -0.4 },
					rot = { -90, 0, 0 },
				},
				ChestLowL = {
					pos = { -0.45, 0, -0.4 },
					rot = { -90, 0, 0 },
				},
				BackR = {
					pos = { 0.4, 0.5, 0.46 },
					rot = { 90, 0, 0 },
				},
				BackL = {
					pos = { -0.4, 0.5, 0.46 },
					rot = { 90, 0, 0 },
				},
				FlankR = {
					pos = { 0.68, 0.1, 0.02 },
					rot = { 0, 0, -90 },
				},
				FlankL = {
					pos = { -0.68, 0.1, 0.02 },
					rot = { 0, 0, 90 },
				},
				ShoulderR = {
					pos = { 0.72, 0.95, 0 },
					rot = { 0, 0, 0 },
				},
				ShoulderL = {
					pos = { -0.72, 0.95, 0 },
					rot = { 0, 0, 0 },
				},
				HipR = {
					pos = { 0.62, -0.85, 0 },
					rot = { 0, 0, -90 },
				},
				HipL = {
					pos = { -0.62, -0.85, 0 },
					rot = { 0, 0, 90 },
				},
			},
			space = "torso",
			tags = { "humanoid" },
			variants = {
				Open = "NormalTorsoOpen",
			},
		},
		NormalTorsoOpen = {
			grade = "Grade4",
			hidden = True,
			layout = {
				neck = { 0, 1, -0.05 },
				shoulder = { 1, 0.55, 0 },
				hip = { 1, -1, 0 },
				tailRoot = { 0, -0.8, 0.42 },
				legExtra = 0,
			},
			pieces = {
				{
					name = "NormalTorsoOpen_Bone",
					offset = { 0.0036, 0.1455, -0.433 },
					role = "Bone",
					size = { 0.7219, 0.3468, 0.1045 },
					tris = 472,
				},
				{
					name = "NormalTorsoOpen_Skin",
					offset = { -0.0002, 0.0446, 0.0598 },
					role = "Skin",
					size = { 2.119, 2.556, 0.9694 },
					tris = 5303,
				},
				{
					name = "NormalTorsoOpen_SkinLight",
					offset = { 0.0046, 0.079, -0.3765 },
					role = "SkinLight",
					size = { 1.344, 1.301, 0.2555 },
					tris = 462,
				},
				{
					name = "NormalTorsoOpen_Void",
					offset = { 0.0036, 0.1513, -0.2514 },
					role = "Void",
					size = { 0.6971, 1.011, 0.5031 },
					tris = 763,
				},
			},
			sided = False,
			slot = "Torso",
			sockets = {
				Chest = {
					pos = { 0, 0.3, -0.5 },
					rot = { -90, 0, 0 },
				},
				Belly = {
					pos = { 0, -0.35, -0.45 },
					rot = { -90, 0, 0 },
				},
				UpperBack = {
					pos = { 0, 0.6, 0.5 },
					rot = { 90, 0, 0 },
				},
				Back = {
					pos = { 0, 0.15, 0.51 },
					rot = { 90, 0, 0 },
				},
				LowerBack = {
					pos = { 0, -0.4, 0.45 },
					rot = { 90, 0, 0 },
				},
				TailRoot = {
					pos = { 0, -0.8, 0.42 },
					rot = { 90, 0, 0 },
				},
				Neck = {
					pos = { 0, 1, 0.05 },
					rot = { 0, 0, 0 },
				},
				ChestR = {
					pos = { 0.32, 0.45, -0.475 },
					rot = { -90, 0, 0 },
				},
				ChestL = {
					pos = { -0.32, 0.45, -0.475 },
					rot = { -90, 0, 0 },
				},
				ChestLowR = {
					pos = { 0.45, 0, -0.4 },
					rot = { -90, 0, 0 },
				},
				ChestLowL = {
					pos = { -0.45, 0, -0.4 },
					rot = { -90, 0, 0 },
				},
				BackR = {
					pos = { 0.4, 0.5, 0.46 },
					rot = { 90, 0, 0 },
				},
				BackL = {
					pos = { -0.4, 0.5, 0.46 },
					rot = { 90, 0, 0 },
				},
				FlankR = {
					pos = { 0.68, 0.1, 0.02 },
					rot = { 0, 0, -90 },
				},
				FlankL = {
					pos = { -0.68, 0.1, 0.02 },
					rot = { 0, 0, 90 },
				},
				ShoulderR = {
					pos = { 0.72, 0.95, 0 },
					rot = { 0, 0, 0 },
				},
				ShoulderL = {
					pos = { -0.72, 0.95, 0 },
					rot = { 0, 0, 0 },
				},
				HipR = {
					pos = { 0.62, -0.85, 0 },
					rot = { 0, 0, -90 },
				},
				HipL = {
					pos = { -0.62, -0.85, 0 },
					rot = { 0, 0, 90 },
				},
			},
			space = "torso",
			tags = { "humanoid" },
		},
		OpenHand = {
			grade = "Grade4",
			pieces = {
				{
					name = "OpenHand_Skin",
					offset = { -0.046, -0.3658, -0.0583 },
					role = "Skin",
					size = { 0.3951, 0.7765, 0.6151 },
					tris = 3309,
				},
				{
					name = "OpenHand_SkinLight",
					offset = { 0.0517, -0.3855, 0.0008 },
					role = "SkinLight",
					size = { 0.1151, 0.1698, 0.497 },
					tris = 191,
				},
			},
			sided = True,
			slot = "Hands",
			space = "hand",
			tags = { "hand" },
		},
		RamHorn = {
			grade = "Grade3",
			pieces = {
				{
					name = "RamHorn_Bone",
					offset = { 0.3309, -0.1925, 0.2923 },
					role = "Bone",
					size = { 0.599, 0.926, 0.9423 },
					tris = 1532,
				},
				{
					name = "RamHorn_BoneDark",
					offset = { 0.0768, 0.0533, 0.2637 },
					role = "BoneDark",
					size = { 0.6099, 0.5015, 0.9046 },
					tris = 659,
				},
				{
					name = "RamHorn_Skin",
					offset = { -0.0003, -0.0403, 0.0025 },
					role = "Skin",
					size = { 0.4769, 0.2507, 0.482 },
					tris = 309,
				},
			},
			sided = True,
			slot = "Horns",
			socket = "Crown",
			space = "surface",
			tags = { "horn", "bone" },
		},
		RibGrowth = {
			count = 1,
			grade = "Grade3",
			pieces = {
				{
					name = "RibGrowth_Bone",
					offset = { -0.0885, 0.3061, -0.2458 },
					role = "Bone",
					size = { 0.3263, 0.5787, 1.336 },
					tris = 2243,
				},
				{
					name = "RibGrowth_Flesh",
					offset = { 0.0006, -0.0192, 0.0001 },
					role = "Flesh",
					size = { 0.3595, 0.181, 1.102 },
					tris = 757,
				},
			},
			sided = True,
			slot = "TorsoGrowths",
			slots = { "TorsoGrowths", "Disfigurements" },
			socket = "FlankR",
			space = "surface",
			tags = { "bone" },
		},
		SerpentBody = {
			grade = "SpecialGrade",
			pieces = {
				{
					name = "SerpentBody_Flesh",
					offset = { -0.1826, -2.221, 0.508 },
					role = "Flesh",
					size = { 1.29, 1.824, 2.824 },
					tris = 1290,
				},
				{
					name = "SerpentBody_Skin",
					offset = { -0.6319, -1.604, 0.9096 },
					role = "Skin",
					size = { 2.682, 3.216, 3.179 },
					tris = 7708,
				},
			},
			sided = False,
			slot = "Legs",
			space = "serpent",
			tags = { "abnormal", "serpent" },
		},
		Shell = {
			grade = "Grade2",
			pieces = {
				{
					name = "Shell_BoneDark",
					offset = { 0.0013, -0.2894, 0.381 },
					role = "BoneDark",
					size = { 1.777, 1.407, 0.262 },
					tris = 1250,
				},
				{
					name = "Shell_SkinDark",
					offset = { 0.0008, -0.3297, 0.1601 },
					role = "SkinDark",
					size = { 1.735, 1.361, 0.6403 },
					tris = 1559,
				},
				{
					name = "Shell_SkinDeep",
					offset = { -0.0005, 0.1567, 0.14 },
					role = "SkinDeep",
					size = { 1.899, 1.389, 0.6409 },
					tris = 1691,
				},
			},
			sided = False,
			slot = "Back",
			socket = "Back",
			space = "body",
			tags = { "armor", "shell" },
		},
		SkullHead = {
			defaults = {
				Eyes = {
					{
						id = "GlowPoint",
						socket = "EyeR",
					},
					{
						id = "GlowPoint",
						socket = "EyeL",
					},
				},
				Mouths = {  },
			},
			grade = "Grade2",
			pieces = {
				{
					name = "SkullHead_Bone",
					offset = { -0.0017, 0.1862, -0.0051 },
					role = "Bone",
					size = { 1.122, 1.231, 1.356 },
					tris = 4115,
				},
				{
					name = "SkullHead_BoneDark",
					offset = { -0.0027, -0.1426, -0.1436 },
					role = "BoneDark",
					size = { 0.8368, 1.549, 0.8701 },
					tris = 1687,
				},
				{
					name = "SkullHead_Teeth",
					offset = { -0.0007, -0.3991, -0.5209 },
					role = "Teeth",
					size = { 0.6455, 0.22, 0.1755 },
					tris = 531,
				},
				{
					name = "SkullHead_Void",
					offset = { 0.0003, 0.0369, -0.5456 },
					role = "Void",
					size = { 0.7322, 0.4625, 0.2663 },
					tris = 665,
				},
			},
			sided = False,
			slot = "Head",
			sockets = {
				Crown = {
					pos = { 0, 0.82, 0.05 },
					rot = { 0, 0, 0 },
				},
				Brow = {
					pos = { 0, 0.4, -0.55 },
					rot = { -60, 0, 0 },
				},
				Face = {
					pos = { 0, 0.05, -0.7 },
					rot = { -90, 0, 0 },
				},
				Mouth = {
					pos = { 0, -0.4, -0.64 },
					rot = { -90, 0, 0 },
				},
				Jaw = {
					pos = { 0, -0.66, -0.2 },
					rot = { 180, 0, 0 },
				},
				BackOfHead = {
					pos = { 0, 0.25, 0.66 },
					rot = { 90, 0, 0 },
				},
				TopR = {
					pos = { 0.33, 0.7, 0 },
					rot = { 0, 0, -30 },
				},
				TopL = {
					pos = { -0.33, 0.7, 0 },
					rot = { 0, 0, 30 },
				},
				EyeR = {
					pos = { 0.23, 0.12, -0.46 },
					rot = { -90, 0, 0 },
				},
				EyeL = {
					pos = { -0.23, 0.12, -0.46 },
					rot = { -90, 0, 0 },
				},
				CheekR = {
					pos = { 0.46, -0.12, -0.35 },
					rot = { -90, 0, -45 },
				},
				CheekL = {
					pos = { -0.46, -0.12, -0.35 },
					rot = { -90, 0, 45 },
				},
				TempleR = {
					pos = { 0.56, 0.3, 0 },
					rot = { 0, 0, -90 },
				},
				TempleL = {
					pos = { -0.56, 0.3, 0 },
					rot = { 0, 0, 90 },
				},
				EarR = {
					pos = { 0.58, 0.05, 0.05 },
					rot = { 0, 0, -90 },
				},
				EarL = {
					pos = { -0.58, 0.05, 0.05 },
					rot = { 0, 0, 90 },
				},
			},
			space = "head",
			tags = { "bone" },
		},
		Spikes = {
			grade = "Grade3",
			pieces = {
				{
					name = "Spikes_Bone",
					offset = { -0.0019, -0.579, 0.2491 },
					role = "Bone",
					size = { 0.215, 1.83, 0.5509 },
					tris = 1572,
				},
				{
					name = "Spikes_SkinDark",
					offset = { 0, -0.6941, 0.0084 },
					role = "SkinDark",
					size = { 0.2405, 1.605, 0.1997 },
					tris = 1426,
				},
			},
			sided = False,
			slot = "Back",
			slots = { "Back", "Disfigurements" },
			socket = "UpperBack",
			space = "body",
			tags = { "bone", "spine" },
		},
		SplayedFoot = {
			grade = "Grade3",
			pieces = {
				{
					name = "SplayedFoot_Claw",
					offset = { -0.0003, 0.0525, -1.046 },
					role = "Claw",
					size = { 0.7691, 0.0832, 0.1876 },
					tris = 318,
				},
				{
					name = "SplayedFoot_Skin",
					offset = { -0.0006, 0.1417, -0.3948 },
					role = "Skin",
					size = { 0.7501, 0.2817, 1.426 },
					tris = 3182,
				},
			},
			sided = True,
			slot = "Feet",
			space = "foot",
			tags = { "foot", "reference" },
		},
		SplitJawHead = {
			defaults = {
				Eyes = {  },
				Mouths = {  },
			},
			grade = "Grade2",
			pieces = {
				{
					name = "SplitJawHead_Eye",
					offset = { -0.005, 0.594, -0.4387 },
					role = "Eye",
					size = { 0.7671, 0.1412, 0.09 },
					tris = 304,
				},
				{
					name = "SplitJawHead_Skin",
					offset = { 0.0004, -0.0446, 0.0659 },
					role = "Skin",
					size = { 1.798, 1.856, 1.535 },
					tris = 5815,
				},
				{
					name = "SplitJawHead_SkinDeep",
					offset = { 0.0026, 0.5901, -0.4089 },
					role = "SkinDeep",
					size = { 0.749, 0.1938, 0.1207 },
					tris = 194,
				},
				{
					name = "SplitJawHead_Teeth",
					offset = { -0, -0.3912, -0.5259 },
					role = "Teeth",
					size = { 1.377, 1.025, 0.1527 },
					tris = 837,
				},
				{
					name = "SplitJawHead_Void",
					offset = { 0.0005, -0.2197, -0.2093 },
					role = "Void",
					size = { 0.7263, 0.9798, 0.797 },
					tris = 850,
				},
			},
			sided = False,
			slot = "Head",
			sockets = {
				Crown = {
					pos = { 0, 0.85, 0.15 },
					rot = { 0, 0, 0 },
				},
				Brow = {
					pos = { 0, 0.55, -0.5 },
					rot = { -60, 0, 0 },
				},
				Face = {
					pos = { 0, 0.3, -0.6 },
					rot = { -90, 0, 0 },
				},
				Mouth = {
					pos = { 0, -0.4, -0.65 },
					rot = { -90, 0, 0 },
				},
				Jaw = {
					pos = { 0, -1, -0.15 },
					rot = { 180, 0, 0 },
				},
				BackOfHead = {
					pos = { 0, 0.4, 0.8 },
					rot = { 90, 0, 0 },
				},
				TopR = {
					pos = { 0.4, 0.75, 0.1 },
					rot = { 0, 0, -30 },
				},
				TopL = {
					pos = { -0.4, 0.75, 0.1 },
					rot = { 0, 0, 30 },
				},
				EyeR = {
					pos = { 0.3, 0.45, -0.52 },
					rot = { -90, 0, 0 },
				},
				EyeL = {
					pos = { -0.3, 0.45, -0.52 },
					rot = { -90, 0, 0 },
				},
				CheekR = {
					pos = { 0.75, -0.2, -0.3 },
					rot = { -90, 0, -45 },
				},
				CheekL = {
					pos = { -0.75, -0.2, -0.3 },
					rot = { -90, 0, 45 },
				},
				TempleR = {
					pos = { 0.65, 0.45, 0 },
					rot = { 0, 0, -90 },
				},
				TempleL = {
					pos = { -0.65, 0.45, 0 },
					rot = { 0, 0, 90 },
				},
				EarR = {
					pos = { 0.66, 0.3, 0.1 },
					rot = { 0, 0, -90 },
				},
				EarL = {
					pos = { -0.66, 0.3, 0.1 },
					rot = { 0, 0, 90 },
				},
			},
			space = "head",
			tags = { "maw", "transformation" },
		},
		StraightHorn = {
			grade = "Grade4",
			pieces = {
				{
					name = "StraightHorn_Bone",
					offset = { 0.0029, 0.5954, 0.0252 },
					role = "Bone",
					size = { 0.1697, 0.7595, 0.1986 },
					tris = 1138,
				},
				{
					name = "StraightHorn_BoneDark",
					offset = { 0.0027, 0.0606, -0.0069 },
					role = "BoneDark",
					size = { 0.2445, 0.4102, 0.2619 },
					tris = 689,
				},
				{
					name = "StraightHorn_Skin",
					offset = { 0, -0.0522, 0.0001 },
					role = "Skin",
					size = { 0.3092, 0.15, 0.3092 },
					tris = 673,
				},
			},
			sided = True,
			slot = "Horns",
			socket = "Crown",
			space = "surface",
			tags = { "horn", "bone" },
		},
		StubHorn = {
			grade = "Grade4",
			pieces = {
				{
					name = "StubHorn_Bone",
					offset = { 0.0014, 0.2214, 0.0111 },
					role = "Bone",
					size = { 0.1575, 0.2703, 0.1625 },
					tris = 581,
				},
				{
					name = "StubHorn_BoneDark",
					offset = { 0.0022, 0.0075, 0.0037 },
					role = "BoneDark",
					size = { 0.2504, 0.3031, 0.2712 },
					tris = 817,
				},
				{
					name = "StubHorn_Skin",
					offset = { 0.0001, -0.0518, 0.0002 },
					role = "Skin",
					size = { 0.3094, 0.1425, 0.3102 },
					tris = 1102,
				},
			},
			sided = True,
			slot = "Horns",
			socket = "Crown",
			space = "surface",
			tags = { "horn", "bone" },
		},
		TalonFoot = {
			grade = "Grade2",
			pieces = {
				{
					name = "TalonFoot_Claw",
					offset = { 0.0017, 0.0571, -0.18 },
					role = "Claw",
					size = { 0.4161, 0.1483, 1.195 },
					tris = 726,
				},
				{
					name = "TalonFoot_SkinDark",
					offset = { 0, 0.1398, -0.2347 },
					role = "SkinDark",
					size = { 0.4202, 0.2606, 0.8823 },
					tris = 2272,
				},
			},
			sided = True,
			slot = "Feet",
			space = "foot",
			tags = { "foot", "bird" },
		},
		TalonHand = {
			grade = "Grade3",
			pieces = {
				{
					name = "TalonHand_Claw",
					offset = { -0.2344, -0.8406, -0.0366 },
					role = "Claw",
					size = { 0.265, 0.8221, 0.5599 },
					tris = 712,
				},
				{
					name = "TalonHand_Skin",
					offset = { -0.0489, -0.5228, -0.0556 },
					role = "Skin",
					size = { 0.4005, 1.089, 0.622 },
					tris = 2616,
				},
				{
					name = "TalonHand_SkinLight",
					offset = { 0.0395, -0.3846, 0.0011 },
					role = "SkinLight",
					size = { 0.1387, 0.1683, 0.5086 },
					tris = 170,
				},
			},
			sided = True,
			slot = "Hands",
			space = "hand",
			tags = { "hand", "claw" },
		},
		Tendril = {
			grade = "Grade2",
			joint = True,
			pieces = {
				{
					name = "Tendril_Flesh",
					offset = { 0.1642, 0.4701, 0.6999 },
					role = "Flesh",
					size = { 0.269, 0.5767, 0.8532 },
					tris = 90,
				},
				{
					name = "Tendril_Skin",
					offset = { 0.1151, 0.3582, 0.6403 },
					role = "Skin",
					size = { 0.5099, 0.9965, 1.56 },
					tris = 2910,
				},
			},
			sided = False,
			slot = "Back",
			socket = "UpperBack",
			space = "body",
			tags = { "tendril" },
		},
		TentacleArm = {
			grade = "Grade2",
			pieces = {
				{
					name = "TentacleArm_Flesh",
					offset = { -0.2505, -0.6705, -0.044 },
					role = "Flesh",
					size = { 0.2775, 1.573, 0.7679 },
					tris = 68,
				},
				{
					name = "TentacleArm_Skin",
					offset = { -0.3771, -0.3564, -0.1778 },
					role = "Skin",
					size = { 0.7394, 2.271, 1.041 },
					tris = 4932,
				},
			},
			pivot = { -0.5, 0.5, 0 },
			sided = True,
			slot = "Arms",
			sockets = {
				Shoulder = {
					pos = { -0.42, 0.72, 0 },
					rot = { 0, 0, 0 },
				},
				UpperArm = {
					pos = { -0.06389, 0.035, 0 },
					rot = { 0, 0, -90 },
				},
				Elbow = {
					pos = { -0.33, -0.35, 0.3193 },
					rot = { 90, 0, 0 },
				},
				Forearm = {
					pos = { -0.05574, -0.7, -0.01 },
					rot = { 0, 0, -90 },
				},
			},
			space = "arm",
			tags = { "arm", "tentacle" },
		},
		ThinArm = {
			grade = "Grade4",
			pieces = {
				{
					name = "ThinArm_Skin",
					offset = { -0.4344, -0.3454, 0.0015 },
					role = "Skin",
					size = { 0.4575, 2.036, 0.4671 },
					tris = 5000,
				},
			},
			pivot = { -0.5, 0.5, 0 },
			sided = True,
			slot = "Arms",
			sockets = {
				Shoulder = {
					pos = { -0.45, 0.72, 0 },
					rot = { 0, 0, 0 },
				},
				UpperArm = {
					pos = { -0.2483, -0.015, 0 },
					rot = { 0, 0, -90 },
				},
				Elbow = {
					pos = { -0.38, -0.45, 0.1989 },
					rot = { 90, 0, 0 },
				},
				Forearm = {
					pos = { -0.2261, -0.85, 0.005 },
					rot = { 0, 0, -90 },
				},
				Hand = {
					pos = { -0.35, -1.3, -0.05 },
					rot = { 0, 0, 0 },
				},
				Palm = {
					pos = { -0.5, -1.55, -0.05 },
					rot = { 0, 0, 90 },
				},
			},
			space = "arm",
			tags = { "arm" },
		},
		ThinLeg = {
			grade = "Grade4",
			pieces = {
				{
					name = "ThinLeg_Skin",
					offset = { 0.0083, 0.0948, -0.0094 },
					role = "Skin",
					size = { 0.494, 2.112, 0.5471 },
					tris = 4998,
				},
			},
			pivot = { 0.5, 1, 0 },
			sided = True,
			slot = "Legs",
			sockets = {
				Thigh = {
					pos = { 0.02, 0.325, -0.1875 },
					rot = { -90, 0, 0 },
				},
				Knee = {
					pos = { 0.02, -0.1, -0.245 },
					rot = { -90, 0, 0 },
				},
				Shin = {
					pos = { 0.125, -0.475, -0.045 },
					rot = { 0, 0, -90 },
				},
				Foot = {
					pos = { 0.02, -1, 0 },
					rot = { 0, 0, 0 },
				},
			},
			space = "leg",
			span = 2,
			tags = { "leg" },
		},
		Tumor = {
			grade = "Grade4",
			pieces = {
				{
					name = "Tumor_Flesh",
					offset = { -0.0806, 0.0974, -0.0191 },
					role = "Flesh",
					size = { 0.3734, 0.3475, 0.5644 },
					tris = 538,
				},
				{
					name = "Tumor_Skin",
					offset = { 0.0994, 0.0948, -0.0648 },
					role = "Skin",
					size = { 0.359, 0.3565, 0.473 },
					tris = 647,
				},
				{
					name = "Tumor_SkinDark",
					offset = { 0.0005, 0.0237, 0.0003 },
					role = "SkinDark",
					size = { 0.6725, 0.1444, 0.6448 },
					tris = 400,
				},
				{
					name = "Tumor_SkinLight",
					offset = { 0.0121, 0.1277, 0.075 },
					role = "SkinLight",
					size = { 0.5441, 0.3905, 0.5044 },
					tris = 915,
				},
			},
			sided = False,
			slot = "Disfigurements",
			slots = { "HeadGrowths", "Disfigurements", "TorsoGrowths", "Back" },
			socket = "ShoulderR",
			space = "surface",
			tags = { "growth", "flesh" },
		},
		Wing = {
			grade = "Grade2",
			joint = True,
			pieces = {
				{
					name = "Wing_Membrane",
					offset = { 1.436, 0.3243, 0.6208 },
					role = "Membrane",
					size = { 2.478, 2.091, 1.006 },
					tris = 2886,
				},
				{
					name = "Wing_Skin",
					offset = { 0.0096, 0.0501, 0.0491 },
					role = "Skin",
					size = { 0.5406, 0.4816, 0.558 },
					tris = 493,
				},
				{
					name = "Wing_SkinDark",
					offset = { 1.337, 0.3555, 0.5587 },
					role = "SkinDark",
					size = { 2.493, 1.92, 1.081 },
					tris = 1619,
				},
			},
			sided = True,
			slot = "Back",
			socket = "BackR",
			space = "body",
			tags = { "wing" },
		},
	},
}
