--!nonstrict
--[[
	Sculpted-mesh components. Every entry of Meshes/Library (generated by
	tools/sculpt/library.py) becomes a component; this module only knows how each
	SPACE is placed on the R6 skeleton and scaled by the body's mass:

	  torso    on the Torso, scaled by TorsoW/H/D; carries the joint layout + torso sockets
	  head     on the Head (or an extra head), scaled by Head around the neck joint
	  arm      on an arm part, thickness × length around the shoulder pivot; defines Hand_<s>…
	  hand     at the arm's Hand socket, scaled by Hand
	  leg      on a leg part, stretched to the visible leg length (legExtra); defines Foot_<s>…
	  foot     at the leg's Foot socket, scaled by Foot
	  surface  at an entry's socket, +Y out of the body (horns, eyes, mouths, growths)
	  body     at an entry's socket position, torso-aligned (tails, wings, tendrils, spikes);
	           these hang on their own Motor6D so the client can sway them
]]

local Library = require(script.Parent.Parent.Meshes.Library)
local Rig = require(script.Parent.Parent.Rig)

local function v3(t)
	return Vector3.new(t[1], t[2], t[3])
end

local function meshScale(ctx, key)
	return Rig.meshScale(ctx:m(key))
end

-- place every piece: offset scaled about `pivot`, size scaled
local function placePieces(ctx, def, anchor, scale, pivot)
	pivot = pivot or Vector3.zero
	for _, piece in ipairs(def.pieces) do
		local off = pivot + (v3(piece.offset) - pivot) * scale
		ctx:mesh(anchor, piece.name, off, v3(piece.size) * scale, piece.role, def.sided)
	end
end

-- sockets: `sided` spaces (arms/legs) get the builder's side suffix (Hand → Hand_R / Hand_E1)
local function placeSockets(ctx, def, anchor, scale, pivot, sided)
	pivot = pivot or Vector3.zero
	for name, s in pairs(def.sockets or {}) do
		local pos = pivot + (v3(s.pos) - pivot) * scale
		ctx:with({ scale = Vector3.one }, function()
			ctx:defineSocket(sided and ctx:sided(name) or name, anchor, { pos.X, pos.Y, pos.Z }, s.rot)
		end)
	end
end

local function hasOwnSocket(ctx, base)
	return ctx.state.sockets[ctx:sided(base)] ~= nil
end

local PLACE = {}

function PLACE.torso(ctx, def)
	local useDef = def
	if ctx.body.flags.OpenChest and def.variants and def.variants.Open then
		useDef = Library.components[def.variants.Open] or def
	end
	local scale = Vector3.new(meshScale(ctx, "TorsoW"), meshScale(ctx, "TorsoH"), meshScale(ctx, "TorsoD"))
	local anchor = ctx:anchor("Torso")
	placePieces(ctx, useDef, anchor, scale)
	ctx:with({ side = 1 }, placeSockets, ctx, def, anchor, scale)
end

function PLACE.head(ctx, def, entry)
	local part = entry.part or ctx:basePart("Head")
	local k = meshScale(ctx, "Head")
	local scale = ctx.scale * k
	local pivot = Vector3.new(0, -0.5, 0) -- the neck joint
	local anchor = ctx:anchor(part)
	ctx:with({ side = 1 }, function()
		placePieces(ctx, def, anchor, scale, pivot)
		placeSockets(ctx, def, anchor, scale, pivot)
	end)
end

function PLACE.arm(ctx, def, entry)
	local part = entry.part or ctx:basePart(ctx.sideName .. " Arm")
	local t, len = meshScale(ctx, "ArmThick"), ctx:m("ArmLength")
	local scale = Vector3.new(t, len, t)
	placePieces(ctx, def, ctx:anchor(part), scale, v3(def.pivot))
	placeSockets(ctx, def, ctx:anchor(part), scale, v3(def.pivot), true)
end

function PLACE.hand(ctx, def)
	if not hasOwnSocket(ctx, "Hand") then
		return -- the arm has no hand (tentacle, scythe …)
	end
	placePieces(ctx, def, ctx:socket(ctx:sided("Hand")), Vector3.one * meshScale(ctx, "Hand"))
end

function PLACE.leg(ctx, def, entry)
	local part = entry.part or ctx:basePart(ctx.sideName .. " Leg")
	local t = meshScale(ctx, "LegThick")
	local stretch = (2 + ctx.layout.legExtra) / (def.span or 2)
	local scale = Vector3.new(t, stretch, t)
	local pivot = Vector3.new(0, 1, 0) -- the hip end of the leg
	placePieces(ctx, def, ctx:anchor(part), scale, pivot)
	placeSockets(ctx, def, ctx:anchor(part), scale, pivot, true)
end

function PLACE.foot(ctx, def)
	if not hasOwnSocket(ctx, "Foot") then
		return
	end
	placePieces(ctx, def, ctx:socket(ctx:sided("Foot")), Vector3.one * meshScale(ctx, "Foot"))
end

-- Legs replaced by one coiling body on the Torso (built once; the R6 legs still animate, unseen).
function PLACE.serpent(ctx, def)
	if ctx.side < 0 then
		return
	end
	local w = meshScale(ctx, "TorsoW")
	ctx:with({ side = 1 }, placePieces, ctx, def, ctx:anchor("Torso"), Vector3.new(w, 1, w))
end

function PLACE.surface(ctx, def)
	placePieces(ctx, def, ctx.at or ctx:socket(def.socket or "Chest"), ctx.scale)
end

-- torso-aligned, on its own joint so it can sway / be animated
function PLACE.body(ctx, def, entry)
	local at = ctx.at or ctx:socket(def.socket or "Back")
	local rot = entry.rot or { 0, 0, 0 }
	local index = 1
	if def.slot == "Tails" then
		index = (ctx.folder:GetAttribute("TailCount") or 0) + 1
		ctx.folder:SetAttribute("TailCount", index)
	end
	local yaw = (index == 1) and 0 or (index % 2 == 0 and 1 or -1) * 24 * math.floor(index / 2)
	local frame = { part = at.part, cf = CFrame.new(at.cf.Position), side = at.side }
	local joint = ctx:with({ scale = Vector3.one }, function()
		return ctx:chain(frame, { 0, 0, 0 }, { rot[1] or 0, (rot[2] or 0) + yaw, rot[3] or 0 }, { { 0.1, 0.1, { 0, 0, 0 } } },
			{ name = def.slot == "Tails" and "Tail" or "Appendage", flesh = false, sway = { amp = def.slot == "Tails" and 6 or 5, speed = 0.9 } })
	end)[1]
	local anchor = { part = joint.anchor.part, cf = CFrame.new(0, joint.length / 2, 0), side = ctx.side }
	placePieces(ctx, def, anchor, ctx.scale)
end

return function(R)
	for id, data in pairs(Library.components) do
		local place = PLACE[data.space]
		local def = {
			id = id,
			slots = data.slots or { data.slot },
			grade = data.grade,
			tags = data.tags,
			hidden = data.hidden,
			defaults = data.defaults,
			layout = data.layout,
			count = data.count,
			params = { socket = data.socket },
			mesh = data,
			build = function(ctx, _, entry)
				place(ctx, data, entry)
			end,
		}
		if data.space == "leg" and data.legExtra then
			def.mutate = function(body)
				body.layout.legExtra += data.legExtra / 2 -- once per side
			end
		end
		R.register(def)
	end
end
