"""Bake a sculpted creature into Roblox-ready meshes.

    python3 tools/sculpt/bake.py husk [--fast] [--no-render] [--budget 0.25]

Outputs (assets/meshes/<Name>/):
    <Bone>_<material>.obj   one MeshPart each, vertices relative to the piece's own center
    <Name>.obj              every piece in one file, in rest-pose world space (single import)
    manifest.lua / .json    bone, material, color, center offset from the bone, size, triangles
Previews (previews/mesh/): <Name>_turnaround.png, _compare.png, _silhouette.png, _skeleton.png
"""
import importlib
import json
import os
import sys
import time

import numpy as np
from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.dirname(HERE))
from sculpt.sdf import mesh_bone, write_obj  # noqa: E402
from sculpt import raster  # noqa: E402
from sculpt import texture  # noqa: E402


def safe(name):
    return name.replace(" ", "")


def bake(mod, fast=False, textured=True, budget=1.0):
    sculpt = mod.build()
    out_dir = os.path.join(ROOT, "assets", "meshes", mod.NAME)
    os.makedirs(out_dir, exist_ok=True)
    for f in os.listdir(out_dir):
        if f.endswith(".obj"):
            os.remove(os.path.join(out_dir, f))
    pieces, render_pieces = [], []
    combined = []
    for bone in sculpt.ops:
        t0 = time.time()
        voxel = mod.VOXEL.get(bone, 0.025) * (1.8 if fast else 1.0)
        verts, faces, normals, face_mat = mesh_bone(sculpt, bone, voxel=voxel,
                                                    max_tris=int(mod.MAX_TRIS.get(bone, 8000) * budget))
        bone_center = np.asarray(mod.BONES[bone], float)
        border = texture.border_flags(faces, face_mat, len(verts))
        sdf = (lambda q, b=bone: sculpt.evaluate(b, q)[0])
        matfn = (lambda q, b=bone: sculpt.evaluate(b, q)[1])
        for mat in sorted(set(face_mat)):
            if not mat:
                continue
            f = faces[face_mat == mat]
            if len(f) < 4:
                continue
            used = np.unique(f)
            lo, hi = verts[used].min(0), verts[used].max(0)
            center = (lo + hi) / 2
            name = f"{safe(bone)}_{mat}"
            write_obj(os.path.join(out_dir, name + ".obj"), name, verts, normals, f, center)
            rgb, material, neon = mod.MATERIALS[mat]
            pieces.append(dict(name=name, bone=bone, material=mat, offset=list(np.round(center - bone_center, 4)),
                               size=list(np.round(hi - lo, 4)), tris=int(len(f))))
            rp = dict(verts=verts, faces=f, normals=normals, color=np.array(rgb) / 255, neon=neon,
                      gloss=0.35 if mat in ("skin", "flesh") else 0.6, name=name)
            if textured:
                vmap, idx, uvs, img = texture.bake_piece(verts, normals, f, border, mat, sdf, matfn=matfn)
                if img is not None:
                    tex_dir = os.path.join(out_dir, "textures")
                    os.makedirs(tex_dir, exist_ok=True)
                    img.save(os.path.join(tex_dir, name + ".png"))
                    rp.update(verts=verts[vmap], normals=normals[vmap], faces=idx, uv=uvs,
                              tex=np.asarray(img.transpose(Image.FLIP_TOP_BOTTOM).transpose(Image.FLIP_TOP_BOTTOM), float) / 255)
            render_pieces.append(rp)
            combined.append((name, verts, normals, f))
        print(f"  {bone:10s} {len(faces):6d} tris  ({time.time() - t0:.1f}s)")
    # single-file import (world rest space)
    with open(os.path.join(out_dir, mod.NAME + ".obj"), "w") as fh:
        base = 1
        for name, verts, normals, f in combined:
            used = np.unique(f)
            remap = -np.ones(len(verts), dtype=int)
            remap[used] = np.arange(len(used))
            fh.write(f"o {name}\n")
            fh.write("".join(f"v {a:.4f} {b:.4f} {c:.4f}\n" for a, b, c in verts[used]))
            fh.write("".join(f"vn {a:.4f} {b:.4f} {c:.4f}\n" for a, b, c in normals[used]))
            ff = remap[f] + base
            fh.write("".join(f"f {a}//{a} {b}//{b} {c}//{c}\n" for a, b, c in ff))
            base += len(used)
    manifest = dict(
        name=mod.NAME,
        bones={k: list(v) for k, v in mod.BONES.items()},
        joints=[list(j) for j in mod.JOINTS],
        materials={k: dict(color=list(v[0]), material=v[1]) for k, v in mod.MATERIALS.items()},
        pieces=pieces,
    )
    with open(os.path.join(out_dir, "manifest.json"), "w") as fh:
        json.dump(manifest, fh, indent=1)
    with open(os.path.join(out_dir, "manifest.lua"), "w") as fh:
        fh.write("-- GENERATED by tools/sculpt/bake.py — mesh manifest for " + mod.NAME + "\nreturn " + to_lua(manifest) + "\n")
    total = sum(p["tris"] for p in pieces)
    print(f"{mod.NAME}: {len(pieces)} MeshParts, {total} triangles → {os.path.relpath(out_dir, ROOT)}")
    return manifest, render_pieces


def to_lua(v, indent=0):
    pad = "\t" * indent
    if isinstance(v, dict):
        items = []
        for k, x in v.items():
            key = k if k.isidentifier() else f'["{k}"]'
            items.append(f"{pad}\t{key} = {to_lua(x, indent + 1)},")
        return "{\n" + "\n".join(items) + f"\n{pad}}}"
    if isinstance(v, (list, tuple)):
        if all(isinstance(x, (int, float, str)) for x in v):
            return "{ " + ", ".join(to_lua(x) for x in v) + " }"
        return "{\n" + "\n".join(f"{pad}\t{to_lua(x, indent + 1)}," for x in v) + f"\n{pad}}}"
    if isinstance(v, str):
        return f'"{v}"'
    if isinstance(v, float):
        return f"{v:.4g}"
    return str(v)


def box_mesh(center, size):
    c, s = np.asarray(center, float), np.asarray(size, float) / 2
    v = np.array([[x, y, z] for x in (-1, 1) for y in (-1, 1) for z in (-1, 1)], float) * s + c
    f = np.array([[0, 1, 3], [0, 3, 2], [4, 6, 7], [4, 7, 5], [0, 4, 5], [0, 5, 1], [2, 3, 7], [2, 7, 6],
                  [0, 2, 6], [0, 6, 4], [1, 5, 7], [1, 7, 3]])
    fn = np.cross(v[f[:, 1]] - v[f[:, 0]], v[f[:, 2]] - v[f[:, 0]])
    # flat shading: duplicate verts per face
    V = v[f].reshape(-1, 3)
    N = np.repeat(fn / np.linalg.norm(fn, axis=1, keepdims=True), 3, axis=0)
    return V, np.arange(len(V)).reshape(-1, 3), N


def previews(mod, pieces):
    out = os.path.join(ROOT, "previews", "mesh")
    os.makedirs(out, exist_ok=True)
    center = (0, 2.7, 0.1)
    views = [raster.render(pieces, yaw, center=center) for yaw in (28, 0, 90, 180, -90)]
    sheet = Image.new("RGB", (560 * 5, 680), (255, 255, 255))
    for i, v in enumerate(views):
        sheet.paste(v, (560 * i, 0))
    ImageDraw.Draw(sheet).text((8, 6), f"{mod.NAME}  (3/4, front, right, back, left)", fill=(20, 20, 20))
    sheet.save(os.path.join(out, f"{mod.NAME}_turnaround.png"))
    ref_path = os.path.join(ROOT, "reference", "reference.png")
    if os.path.exists(ref_path):
        ref = Image.open(ref_path).convert("RGBA")
        bg = Image.new("RGBA", ref.size, (237, 237, 242, 255))
        ref = Image.alpha_composite(bg, ref).convert("RGB")
        ref = ref.resize((int(ref.width * 680 / ref.height), 680))
        sil = raster.render(pieces, 28, center=center, silhouette=True)
        cmp_img = Image.new("RGB", (ref.width + 560 * 2, 680), (255, 255, 255))
        cmp_img.paste(ref, (0, 0))
        cmp_img.paste(views[0], (ref.width, 0))
        cmp_img.paste(sil, (ref.width + 560, 0))
        ImageDraw.Draw(cmp_img).text((8, 6), "reference  |  mesh  |  silhouette only (no materials)", fill=(20, 20, 20))
        cmp_img.save(os.path.join(out, f"{mod.NAME}_compare.png"))
    # the R6 skeleton the meshes ride on (invisible in game)
    sizes = {"Torso": (2, 2, 1), "Head": (2, 1, 1), "Right Arm": (1, 2, 1), "Left Arm": (1, 2, 1),
             "Right Leg": (1, 2, 1), "Left Leg": (1, 2, 1)}
    boxes = []
    for bone, sz in sizes.items():
        V, F, N = box_mesh(mod.BONES[bone], sz)
        boxes.append(dict(verts=V, faces=F, normals=N, color=(0.35, 0.55, 0.9), gloss=0))
    skel = raster.render(boxes, 28, center=center)
    ghost = [dict(p, color=np.clip(np.array(p["color"]) * 0.5 + 0.45, 0, 1)) for p in pieces]
    both = Image.blend(raster.render(ghost, 28, center=center), skel, 0.45)
    s2 = Image.new("RGB", (560 * 3, 680), (255, 255, 255))
    s2.paste(skel, (0, 0))
    s2.paste(both, (560, 0))
    s2.paste(views[0], (1120, 0))
    ImageDraw.Draw(s2).text((8, 6), "R6 skeleton (invisible)  |  overlay  |  visible mesh body", fill=(20, 20, 20))
    s2.save(os.path.join(out, f"{mod.NAME}_skeleton.png"))


if __name__ == "__main__":
    mod = importlib.import_module("sculpt." + sys.argv[1])
    budget = float(sys.argv[sys.argv.index("--budget") + 1]) if "--budget" in sys.argv else 1.0
    manifest, pieces = bake(mod, fast="--fast" in sys.argv, textured="--no-texture" not in sys.argv, budget=budget)
    if "--no-render" not in sys.argv:
        previews(mod, pieces)
