--[[
	RED CREATURE — R6 build script (GENERATED by tools/build.py; edit the spec, not this file)

	HOW TO USE (Roblox Studio):
	  • New creature: paste this whole file into the Command Bar (View → Command Bar) and press Enter.
	    A model named CONFIG.MODEL_NAME appears at the origin.
	  • Convert an existing R6 rig: select the rig in the Explorer first, then run it.
	  • Player character: rename the result "StarterCharacter" and move it into StarterPlayer.
	    Copy the "Animate" LocalScript from your own character (Play → Workspace → <you>) into it.

	LAYOUT OF THIS FILE
	  1. CONFIG
	  2. MATERIALS / COLORS
	  3. R6 BASE BODY
	  4. JOINTS (Motor6Ds) — standard R6 names + hierarchy, hunch baked into C0
	  5. CREATURE GEOMETRY — head, eyes, torso, beige flesh, chest cavity, arms, legs, tail
	  6. TAIL CHAIN (animatable Motor6Ds)
	  7. BUILD (welds every piece to its R6 body part)
	  8. RAGDOLL ON DEATH + TAIL SWAY
	  9. ANIMATION NOTES
]]

-- 1. CONFIG ------------------------------------------------------------------
local CONFIG = {
	MODEL_NAME = "RedCreature",
	SCALE = 1.35,             -- whole-rig scale via Model:ScaleTo (1 = classic R6 size)
	HIDE_BASE_BODY = true,    -- R6 parts stay (joints, physics) but turn invisible
	ADJUST_JOINTS = true,     -- apply the hunched joint layout from section 4
	RAGDOLL_ON_DEATH = true,
	TAIL_SWAY = true,
	ANCHORED = false,
}

-- 2. MATERIALS / COLORS --------------------------------------------------------
local PALETTE = {
	red = { Color3.fromRGB(148, 32, 40), Enum.Material.SmoothPlastic },
	red_hi = { Color3.fromRGB(172, 50, 56), Enum.Material.SmoothPlastic },
	red_dark = { Color3.fromRGB(104, 20, 28), Enum.Material.SmoothPlastic },
	red_deep = { Color3.fromRGB(58, 10, 16), Enum.Material.SmoothPlastic },
	beige = { Color3.fromRGB(204, 186, 150), Enum.Material.SmoothPlastic },
	beige_dark = { Color3.fromRGB(158, 136, 102), Enum.Material.SmoothPlastic },
	cavity_rim = { Color3.fromRGB(46, 28, 26), Enum.Material.Slate },
	cavity = { Color3.fromRGB(10, 8, 8), Enum.Material.Slate },
	claw = { Color3.fromRGB(28, 20, 20), Enum.Material.SmoothPlastic },
	claw_tip = { Color3.fromRGB(196, 190, 180), Enum.Material.SmoothPlastic },
	spot = { Color3.fromRGB(36, 8, 12), Enum.Material.SmoothPlastic },
	eye = { Color3.fromRGB(228, 226, 214), Enum.Material.Neon },
}

-- 3. R6 BASE BODY --------------------------------------------------------------
local R6_SIZES = {
	HumanoidRootPart = Vector3.new(2, 2, 1),
	Torso = Vector3.new(2, 2, 1),
	Head = Vector3.new(2, 1, 1),
	["Right Arm"] = Vector3.new(1, 2, 1),
	["Left Arm"] = Vector3.new(1, 2, 1),
	["Right Leg"] = Vector3.new(1, 2, 1),
	["Left Leg"] = Vector3.new(1, 2, 1),
}

-- 4. JOINTS -------------------------------------------------------------------
-- { name, Part0, Part1, C0 position, C1 position, rotation }
local ROTATIONS = {
	root = CFrame.new(0, 0, 0, -1, 0, 0, 0, 0, 1, 0, 1, 0),
	right = CFrame.new(0, 0, 0, 0, 0, 1, 0, 1, 0, -1, 0, 0),
	left = CFrame.new(0, 0, 0, 0, 0, -1, 0, 1, 0, 1, 0, 0),
}
local JOINTS = {
	{ "RootJoint", "HumanoidRootPart", "Torso", {0, 0, 0}, {0, 0, 0}, "root" },
	{ "Neck", "Torso", "Head", {0, 0.35, -0.95}, {0, -0.5, 0}, "root" },
	{ "Right Shoulder", "Torso", "Right Arm", {1.3, 0.3, -0.35}, {-0.5, 0.5, 0}, "right" },
	{ "Left Shoulder", "Torso", "Left Arm", {-1.3, 0.3, -0.35}, {0.5, 0.5, 0}, "left" },
	{ "Right Hip", "Torso", "Right Leg", {1.15, -1, 0.05}, {0.5, 1, 0}, "right" },
	{ "Left Hip", "Torso", "Left Leg", {-1.15, -1, 0.05}, {-0.5, 1, 0}, "left" },
}

-- 5. CREATURE GEOMETRY ---------------------------------------------------------
-- { group, name, attached R6 part, position, size, rotation (deg XYZ), palette key }
-- Every piece is an ellipsoid (Part + Sphere SpecialMesh) welded to its body part,
-- so it follows that part through every animation.
local PIECES = {
	-- Head
	{"Head", "Cranium", "Head", {0, 0.4, 0.3}, {1.95, 1.75, 2.35}, {38, 0, 0}, "red"},
	{"Head", "CraniumBack", "Head", {0.05, 0.85, 0.75}, {1.55, 1.15, 1.45}, {25, 0, 6}, "red_hi"},
	{"Head", "Face", "Head", {0, -0.1, -0.5}, {1.65, 1.25, 1.15}, {-12, 0, 0}, "red"},
	{"Head", "Snout", "Head", {0, -0.35, -0.85}, {1.2, 0.8, 0.7}, {-25, 0, 0}, "red_hi"},
	{"Head", "Brow", "Head", {0.05, 0.3, -0.72}, {1.5, 0.38, 0.62}, {-30, 0, 4}, "red"},
	{"Head", "BrowCrease", "Head", {0.05, 0.5, -0.55}, {1.1, 0.12, 0.4}, {-30, 0, 4}, "red_dark"},
	{"Head", "FoldR1", "Head", {0.82, 0.4, 0.15}, {0.34, 0.3, 1.5}, {38, 0, -10}, "red_hi"},
	{"Head", "FoldR2", "Head", {0.78, 0, 0.1}, {0.3, 0.22, 1.3}, {30, 0, -18}, "red_dark"},
	{"Head", "FoldL1", "Head", {-0.84, 0.48, 0.25}, {0.34, 0.32, 1.6}, {40, 0, 12}, "red_hi"},
	{"Head", "FoldL2", "Head", {-0.8, 0.05, 0.05}, {0.3, 0.22, 1.2}, {28, 0, 20}, "red_dark"},
	{"Head", "FoldTop", "Head", {0, 1.15, 0.45}, {1.1, 0.22, 0.7}, {35, 0, 0}, "red_dark"},
	{"Head", "Spot1", "Head", {0.25, 1.22, 0.05}, {0.26, 0.12, 0.24}, {30, 0, 0}, "spot"},
	{"Head", "Spot2", "Head", {-0.15, 1.3, 0.35}, {0.3, 0.12, 0.26}, {35, 0, 0}, "spot"},
	{"Head", "Spot3", "Head", {0.5, 1.02, 0.45}, {0.2, 0.1, 0.2}, {35, 0, -30}, "spot"},
	{"Head", "Spot4", "Head", {-0.42, 1.1, -0.02}, {0.18, 0.1, 0.18}, {25, 0, 30}, "spot"},
	{"Head", "Spot5", "Head", {0.05, 1.05, -0.28}, {0.16, 0.09, 0.16}, {20, 0, 0}, "spot"},
	{"Head", "Spot6", "Head", {0.35, 1.32, 0.55}, {0.14, 0.08, 0.14}, {40, 0, 0}, "spot"},
	{"Head", "Tendril1A", "Head", {-0.42, -0.7, -0.88}, {0.28, 0.62, 0.3}, {-8, 0, 10}, "red"},
	{"Head", "Tendril1B", "Head", {-0.481, -1.05, -0.92}, {0.22, 0.44, 0.24}, {-4, 0, 16}, "red_dark"},
	{"Head", "Tendril2A", "Head", {-0.21, -0.7, -0.88}, {0.28, 0.62, 0.3}, {-8, 0, 4}, "red"},
	{"Head", "Tendril2B", "Head", {-0.236, -1.14, -0.92}, {0.22, 0.56, 0.24}, {-4, 0, 6.4}, "red_hi"},
	{"Head", "Tendril3A", "Head", {0, -0.7, -0.88}, {0.28, 0.62, 0.3}, {-8, 0, -2}, "red"},
	{"Head", "Tendril3B", "Head", {0.008, -1.188, -0.92}, {0.22, 0.624, 0.24}, {-4, 0, -3.2}, "red_dark"},
	{"Head", "Tendril4A", "Head", {0.21, -0.7, -0.88}, {0.28, 0.62, 0.3}, {-8, 0, -6}, "red"},
	{"Head", "Tendril4B", "Head", {0.244, -1.128, -0.92}, {0.22, 0.544, 0.24}, {-4, 0, -9.6}, "red_hi"},
	{"Head", "Tendril5A", "Head", {0.42, -0.7, -0.88}, {0.28, 0.62, 0.3}, {-8, 0, -12}, "red"},
	{"Head", "Tendril5B", "Head", {0.489, -1.032, -0.92}, {0.22, 0.416, 0.24}, {-4, 0, -19.2}, "red_dark"},
	-- Eyes
	{"Eyes", "RightSocket", "Head", {0.7, 0.05, -0.62}, {0.4, 0.36, 0.3}, {0, -50, 0}, "red_deep"},
	{"Eyes", "RightEye", "Head", {0.76, 0.05, -0.68}, {0.2, 0.19, 0.14}, {0, -50, 0}, "eye"},
	{"Eyes", "LeftSocket", "Head", {-0.7, 0.05, -0.62}, {0.4, 0.36, 0.3}, {0, 50, 0}, "red_deep"},
	{"Eyes", "LeftEye", "Head", {-0.76, 0.05, -0.68}, {0.2, 0.19, 0.14}, {0, 50, 0}, "eye"},
	-- Torso
	{"Torso", "Hump", "Torso", {0, 0.75, 0.4}, {2.8, 2.6, 2.3}, {-28, 0, 0}, "red"},
	{"Torso", "HumpTop", "Torso", {0.1, 1.4, 0.35}, {2.2, 1.3, 1.8}, {-32, 0, 5}, "red_hi"},
	{"Torso", "HumpRidge", "Torso", {-0.3, 1.05, 0.95}, {1.6, 0.3, 1.2}, {-40, 0, 10}, "red_dark"},
	{"Torso", "RightShoulderMass", "Torso", {1.2, 0.6, -0.15}, {1.45, 1.5, 1.8}, {0, 0, 22}, "red"},
	{"Torso", "RightShoulderFold", "Torso", {1.25, 1, 0.1}, {1, 0.32, 1.4}, {-10, 0, 30}, "red_hi"},
	{"Torso", "RightNeckWrap", "Torso", {0.72, 0.75, -0.7}, {1.1, 0.95, 1.15}, {-20, 0, 30}, "red"},
	{"Torso", "RightFlank", "Torso", {0.95, -0.3, 0.15}, {0.7, 1.5, 1.2}, {0, 0, 5}, "red"},
	{"Torso", "PelvisBack", "Torso", {0, -0.7, 0.25}, {2.4, 1.2, 1.4}, {10, 0, 0}, "red"},
	{"Torso", "LeftShoulderMass", "Torso", {-1.2, 0.6, -0.15}, {1.45, 1.5, 1.8}, {0, 0, -22}, "red"},
	{"Torso", "LeftShoulderFold", "Torso", {-1.25, 1, 0.1}, {1, 0.32, 1.4}, {-10, 0, -30}, "red_hi"},
	{"Torso", "LeftNeckWrap", "Torso", {-0.72, 0.75, -0.7}, {1.1, 0.95, 1.15}, {-20, 0, -30}, "red"},
	{"Torso", "LeftFlank", "Torso", {-0.95, -0.3, 0.15}, {0.7, 1.5, 1.2}, {0, 0, -5}, "red"},
	{"Torso", "LeftShoulderFold2", "Torso", {-1.25, 0.25, -0.75}, {0.3, 1.1, 0.45}, {0, 0, -12}, "red_dark"},
	-- BeigeFlesh
	{"BeigeFlesh", "Chest", "Torso", {0.05, 0.1, -0.35}, {2.35, 2, 1.4}, {0, 0, 0}, "beige"},
	{"BeigeFlesh", "RightPec", "Torso", {0.7, 0.45, -0.75}, {1, 1.1, 0.65}, {0, 0, -10}, "beige"},
	{"BeigeFlesh", "LeftPec", "Torso", {-0.7, 0.4, -0.72}, {0.95, 1, 0.6}, {0, 0, 10}, "beige"},
	{"BeigeFlesh", "Belly", "Torso", {0, -0.7, -0.3}, {2, 1.1, 1.3}, {0, 0, 0}, "beige"},
	{"BeigeFlesh", "Groin", "Torso", {0, -1.1, -0.25}, {1.1, 0.7, 1}, {0, 0, 0}, "beige"},
	{"BeigeFlesh", "RightRib1", "Torso", {0.78, 0.75, -0.943}, {0.62, 0.1, 0.22}, {0, 12, -12}, "beige_dark"},
	{"BeigeFlesh", "LeftRib1", "Torso", {-0.8, 0.71, -0.912}, {0.55, 0.1, 0.22}, {0, -12, 12}, "beige_dark"},
	{"BeigeFlesh", "RightRib2", "Torso", {0.78, 0.48, -0.956}, {0.62, 0.1, 0.22}, {0, 12, -9}, "beige_dark"},
	{"BeigeFlesh", "LeftRib2", "Torso", {-0.8, 0.44, -0.926}, {0.55, 0.1, 0.22}, {0, -12, 9}, "beige_dark"},
	{"BeigeFlesh", "RightRib3", "Torso", {0.78, 0.21, -0.97}, {0.62, 0.1, 0.22}, {0, 12, -6}, "beige_dark"},
	{"BeigeFlesh", "LeftRib3", "Torso", {-0.8, 0.17, -0.94}, {0.55, 0.1, 0.22}, {0, -12, 6}, "beige_dark"},
	{"BeigeFlesh", "RightRib4", "Torso", {0.78, -0.06, -0.977}, {0.62, 0.1, 0.22}, {0, 12, -3}, "beige_dark"},
	{"BeigeFlesh", "LeftRib4", "Torso", {-0.8, -0.1, -0.947}, {0.55, 0.1, 0.22}, {0, -12, 3}, "beige_dark"},
	{"BeigeFlesh", "BellyRidge1", "Torso", {0, -0.55, -0.93}, {1.45, 0.09, 0.3}, {0, 0, 0}, "beige_dark"},
	{"BeigeFlesh", "BellyRidge2", "Torso", {0, -0.8, -0.9}, {1.33, 0.09, 0.3}, {0, 0, 0}, "beige_dark"},
	{"BeigeFlesh", "BellyRidge3", "Torso", {0, -1.05, -0.87}, {1.21, 0.09, 0.3}, {0, 0, 0}, "beige_dark"},
	{"BeigeFlesh", "BellyRidge4", "Torso", {0, -1.3, -0.84}, {1.09, 0.09, 0.3}, {0, 0, 0}, "beige_dark"},
	-- Cavity
	{"Cavity", "CavityRim", "Torso", {-0.15, 0.1, -1}, {1.45, 2.05, 0.36}, {0, 0, 6}, "cavity_rim"},
	{"Cavity", "Cavity", "Torso", {-0.15, 0.1, -1.07}, {1.28, 1.88, 0.32}, {0, 0, 6}, "cavity"},
	{"Cavity", "CavityDrip", "Torso", {-0.02, -0.85, -1}, {0.45, 0.8, 0.24}, {0, 0, -4}, "cavity"},
	-- RightArm
	{"RightArm", "Deltoid", "Right Arm", {0.05, 0.85, 0}, {1.35, 0.95, 1.35}, {0, 0, 10}, "red_hi"},
	{"RightArm", "UpperArm", "Right Arm", {0.06, 0.25, 0.02}, {1.2, 1.7, 1.2}, {0, 0, 0}, "red"},
	{"RightArm", "Elbow", "Right Arm", {0.12, -0.5, 0.22}, {0.9, 0.7, 0.85}, {0, 0, 0}, "red_dark"},
	{"RightArm", "Forearm", "Right Arm", {0.08, -0.95, -0.08}, {1.15, 1.7, 1.1}, {8, 0, 0}, "red"},
	{"RightArm", "ForearmBeige", "Right Arm", {-0.38, -0.85, -0.2}, {0.45, 1.6, 0.75}, {8, 0, 4}, "beige"},
	{"RightArm", "ForearmRidge", "Right Arm", {0.48, -0.8, -0.1}, {0.3, 1.3, 0.6}, {8, 0, -4}, "red_hi"},
	{"RightArm", "Fist", "Right Arm", {0.08, -1.85, -0.18}, {1.3, 1.1, 1.25}, {0, 0, 0}, "red"},
	{"RightArm", "Thumb", "Right Arm", {-0.48, -1.75, -0.58}, {0.4, 0.7, 0.45}, {-20, 0, 25}, "red_hi"},
	{"RightArm", "Finger1", "Right Arm", {-0.36, -2.18, -0.52}, {0.36, 0.58, 0.62}, {-30, 0, 0}, "red_hi"},
	{"RightArm", "Claw1", "Right Arm", {-0.36, -2.4, -0.25}, {0.18, 0.22, 0.3}, {20, 0, 0}, "claw"},
	{"RightArm", "Finger2", "Right Arm", {-0.08, -2.18, -0.52}, {0.36, 0.58, 0.62}, {-30, 0, 0}, "red_hi"},
	{"RightArm", "Claw2", "Right Arm", {-0.08, -2.4, -0.25}, {0.18, 0.22, 0.3}, {20, 0, 0}, "claw"},
	{"RightArm", "Finger3", "Right Arm", {0.2, -2.18, -0.52}, {0.36, 0.58, 0.62}, {-30, 0, 0}, "red_hi"},
	{"RightArm", "Claw3", "Right Arm", {0.2, -2.4, -0.25}, {0.18, 0.22, 0.3}, {20, 0, 0}, "claw"},
	{"RightArm", "Finger4", "Right Arm", {0.47, -2.18, -0.52}, {0.36, 0.58, 0.62}, {-30, 0, 0}, "red_hi"},
	{"RightArm", "Claw4", "Right Arm", {0.47, -2.4, -0.25}, {0.18, 0.22, 0.3}, {20, 0, 0}, "claw"},
	{"RightArm", "BeigeRidge1", "Right Arm", {-0.52, -0.4, -0.28}, {0.18, 0.08, 0.6}, {8, 0, 4}, "beige_dark"},
	{"RightArm", "BeigeRidge2", "Right Arm", {-0.52, -0.75, -0.28}, {0.18, 0.08, 0.6}, {8, 0, 4}, "beige_dark"},
	{"RightArm", "BeigeRidge3", "Right Arm", {-0.52, -1.1, -0.28}, {0.18, 0.08, 0.6}, {8, 0, 4}, "beige_dark"},
	{"RightArm", "BeigeRidge4", "Right Arm", {-0.52, -1.45, -0.28}, {0.18, 0.08, 0.6}, {8, 0, 4}, "beige_dark"},
	-- LeftArm
	{"LeftArm", "Deltoid", "Left Arm", {-0.05, 0.85, 0}, {1.35, 0.95, 1.35}, {0, 0, -10}, "red_hi"},
	{"LeftArm", "UpperArm", "Left Arm", {-0.06, 0.25, 0.02}, {1.2, 1.7, 1.2}, {0, 0, 0}, "red"},
	{"LeftArm", "Elbow", "Left Arm", {-0.12, -0.5, 0.22}, {0.9, 0.7, 0.85}, {0, 0, 0}, "red_dark"},
	{"LeftArm", "Forearm", "Left Arm", {-0.08, -0.95, -0.08}, {1.15, 1.7, 1.1}, {8, 0, 0}, "red"},
	{"LeftArm", "ForearmBeige", "Left Arm", {0.38, -0.85, -0.2}, {0.45, 1.6, 0.75}, {8, 0, -4}, "beige"},
	{"LeftArm", "ForearmRidge", "Left Arm", {-0.48, -0.8, -0.1}, {0.3, 1.3, 0.6}, {8, 0, 4}, "red_hi"},
	{"LeftArm", "Fist", "Left Arm", {-0.08, -1.85, -0.18}, {1.3, 1.1, 1.25}, {0, 0, 0}, "red"},
	{"LeftArm", "Thumb", "Left Arm", {0.48, -1.75, -0.58}, {0.4, 0.7, 0.45}, {-20, 0, -25}, "red_hi"},
	{"LeftArm", "Finger1", "Left Arm", {0.36, -2.18, -0.52}, {0.36, 0.58, 0.62}, {-30, 0, 0}, "red_hi"},
	{"LeftArm", "Claw1", "Left Arm", {0.36, -2.4, -0.25}, {0.18, 0.22, 0.3}, {20, 0, 0}, "claw"},
	{"LeftArm", "Finger2", "Left Arm", {0.08, -2.18, -0.52}, {0.36, 0.58, 0.62}, {-30, 0, 0}, "red_hi"},
	{"LeftArm", "Claw2", "Left Arm", {0.08, -2.4, -0.25}, {0.18, 0.22, 0.3}, {20, 0, 0}, "claw"},
	{"LeftArm", "Finger3", "Left Arm", {-0.2, -2.18, -0.52}, {0.36, 0.58, 0.62}, {-30, 0, 0}, "red_hi"},
	{"LeftArm", "Claw3", "Left Arm", {-0.2, -2.4, -0.25}, {0.18, 0.22, 0.3}, {20, 0, 0}, "claw"},
	{"LeftArm", "Finger4", "Left Arm", {-0.47, -2.18, -0.52}, {0.36, 0.58, 0.62}, {-30, 0, 0}, "red_hi"},
	{"LeftArm", "Claw4", "Left Arm", {-0.47, -2.4, -0.25}, {0.18, 0.22, 0.3}, {20, 0, 0}, "claw"},
	{"LeftArm", "BeigeRidge1", "Left Arm", {0.52, -0.4, -0.28}, {0.18, 0.08, 0.6}, {8, 0, -4}, "beige_dark"},
	{"LeftArm", "BeigeRidge2", "Left Arm", {0.52, -0.75, -0.28}, {0.18, 0.08, 0.6}, {8, 0, -4}, "beige_dark"},
	{"LeftArm", "BeigeRidge3", "Left Arm", {0.52, -1.1, -0.28}, {0.18, 0.08, 0.6}, {8, 0, -4}, "beige_dark"},
	{"LeftArm", "BeigeRidge4", "Left Arm", {0.52, -1.45, -0.28}, {0.18, 0.08, 0.6}, {8, 0, -4}, "beige_dark"},
	-- RightLeg
	{"RightLeg", "Thigh", "Right Leg", {0.08, 0.5, 0.08}, {1.35, 1.55, 1.4}, {0, 0, 0}, "red"},
	{"RightLeg", "ThighBeige", "Right Leg", {-0.1, 0.4, -0.4}, {1.05, 1.5, 0.85}, {-4, 0, 0}, "beige"},
	{"RightLeg", "Knee", "Right Leg", {0.02, -0.18, -0.12}, {1, 0.75, 0.95}, {0, 0, 0}, "red_hi"},
	{"RightLeg", "Shin", "Right Leg", {0.02, -0.42, 0.05}, {0.95, 1.3, 1}, {0, 0, 0}, "red"},
	{"RightLeg", "CalfBeige", "Right Leg", {-0.32, -0.38, 0.05}, {0.38, 1.1, 0.62}, {0, 0, 4}, "beige"},
	{"RightLeg", "Ankle", "Right Leg", {0, -0.78, 0.08}, {0.82, 0.45, 0.85}, {0, 0, 0}, "red"},
	{"RightLeg", "Foot", "Right Leg", {0, -0.8, -0.5}, {1.15, 0.42, 1.7}, {0, 0, 0}, "red"},
	{"RightLeg", "Heel", "Right Leg", {0, -0.82, 0.38}, {0.72, 0.36, 0.6}, {0, 0, 0}, "red_dark"},
	{"RightLeg", "Toe1", "Right Leg", {-0.38, -0.87, -1.35}, {0.3, 0.26, 0.95}, {0, 8, 0}, "red"},
	{"RightLeg", "ToeClaw1", "Right Leg", {-0.444, -0.92, -1.85}, {0.17, 0.12, 0.3}, {-10, 8, 0}, "claw"},
	{"RightLeg", "Toe2", "Right Leg", {-0.13, -0.87, -1.35}, {0.3, 0.26, 0.95}, {0, 3, 0}, "red_hi"},
	{"RightLeg", "ToeClaw2", "Right Leg", {-0.154, -0.92, -1.85}, {0.17, 0.12, 0.3}, {-10, 3, 0}, "claw"},
	{"RightLeg", "Toe3", "Right Leg", {0.12, -0.87, -1.35}, {0.3, 0.26, 0.95}, {0, -3, 0}, "red"},
	{"RightLeg", "ToeClaw3", "Right Leg", {0.144, -0.92, -1.85}, {0.17, 0.12, 0.3}, {-10, -3, 0}, "claw"},
	{"RightLeg", "Toe4", "Right Leg", {0.37, -0.87, -1.35}, {0.3, 0.26, 0.95}, {0, -9, 0}, "red_hi"},
	{"RightLeg", "ToeClaw4", "Right Leg", {0.442, -0.92, -1.85}, {0.17, 0.12, 0.3}, {-10, -9, 0}, "claw"},
	{"RightLeg", "ThighRidge1", "Right Leg", {-0.15, 0.85, -0.76}, {0.7, 0.08, 0.2}, {0, 0, 0}, "beige_dark"},
	{"RightLeg", "ThighRidge2", "Right Leg", {-0.15, 0.55, -0.76}, {0.7, 0.08, 0.2}, {0, 0, 0}, "beige_dark"},
	{"RightLeg", "ThighRidge3", "Right Leg", {-0.15, 0.25, -0.76}, {0.7, 0.08, 0.2}, {0, 0, 0}, "beige_dark"},
	-- LeftLeg
	{"LeftLeg", "Thigh", "Left Leg", {-0.08, 0.5, 0.08}, {1.35, 1.55, 1.4}, {0, 0, 0}, "red"},
	{"LeftLeg", "ThighBeige", "Left Leg", {0.1, 0.4, -0.4}, {1.05, 1.5, 0.85}, {-4, 0, 0}, "beige"},
	{"LeftLeg", "Knee", "Left Leg", {-0.02, -0.18, -0.12}, {1, 0.75, 0.95}, {0, 0, 0}, "red_hi"},
	{"LeftLeg", "Shin", "Left Leg", {-0.02, -0.42, 0.05}, {0.95, 1.3, 1}, {0, 0, 0}, "red"},
	{"LeftLeg", "CalfBeige", "Left Leg", {0.32, -0.38, 0.05}, {0.38, 1.1, 0.62}, {0, 0, -4}, "beige"},
	{"LeftLeg", "Ankle", "Left Leg", {0, -0.78, 0.08}, {0.82, 0.45, 0.85}, {0, 0, 0}, "red"},
	{"LeftLeg", "Foot", "Left Leg", {0, -0.8, -0.5}, {1.15, 0.42, 1.7}, {0, 0, 0}, "red"},
	{"LeftLeg", "Heel", "Left Leg", {0, -0.82, 0.38}, {0.72, 0.36, 0.6}, {0, 0, 0}, "red_dark"},
	{"LeftLeg", "Toe1", "Left Leg", {0.38, -0.87, -1.35}, {0.3, 0.26, 0.95}, {0, -8, 0}, "red"},
	{"LeftLeg", "ToeClaw1", "Left Leg", {0.444, -0.92, -1.85}, {0.17, 0.12, 0.3}, {-10, -8, 0}, "claw"},
	{"LeftLeg", "Toe2", "Left Leg", {0.13, -0.87, -1.35}, {0.3, 0.26, 0.95}, {0, -3, 0}, "red_hi"},
	{"LeftLeg", "ToeClaw2", "Left Leg", {0.154, -0.92, -1.85}, {0.17, 0.12, 0.3}, {-10, -3, 0}, "claw"},
	{"LeftLeg", "Toe3", "Left Leg", {-0.12, -0.87, -1.35}, {0.3, 0.26, 0.95}, {0, 3, 0}, "red"},
	{"LeftLeg", "ToeClaw3", "Left Leg", {-0.144, -0.92, -1.85}, {0.17, 0.12, 0.3}, {-10, 3, 0}, "claw"},
	{"LeftLeg", "Toe4", "Left Leg", {-0.37, -0.87, -1.35}, {0.3, 0.26, 0.95}, {0, 9, 0}, "red_hi"},
	{"LeftLeg", "ToeClaw4", "Left Leg", {-0.442, -0.92, -1.85}, {0.17, 0.12, 0.3}, {-10, 9, 0}, "claw"},
	{"LeftLeg", "ThighRidge1", "Left Leg", {0.15, 0.85, -0.76}, {0.7, 0.08, 0.2}, {0, 0, 0}, "beige_dark"},
	{"LeftLeg", "ThighRidge2", "Left Leg", {0.15, 0.55, -0.76}, {0.7, 0.08, 0.2}, {0, 0, 0}, "beige_dark"},
	{"LeftLeg", "ThighRidge3", "Left Leg", {0.15, 0.25, -0.76}, {0.7, 0.08, 0.2}, {0, 0, 0}, "beige_dark"},
	-- Tail
	{"Tail", "Tail1Flesh", "Tail1", {0, 0, 0}, {0.92, 1.282, 0.92}, {0, 0, 0}, "red"},
	{"Tail", "Tail1Underside", "Tail1", {0.115, 0, 0.161}, {0.598, 1.14, 0.644}, {0, 0, 0}, "red_dark"},
	{"Tail", "Tail2Flesh", "Tail2", {0, 0, 0}, {0.76, 1.282, 0.76}, {0, 0, 0}, "red_hi"},
	{"Tail", "Tail2Underside", "Tail2", {0.095, 0, 0.133}, {0.494, 1.14, 0.532}, {0, 0, 0}, "red_dark"},
	{"Tail", "Tail3Flesh", "Tail3", {0, 0, 0}, {0.6, 1.215, 0.6}, {0, 0, 0}, "red"},
	{"Tail", "Tail3Underside", "Tail3", {0.075, 0, 0.105}, {0.39, 1.08, 0.42}, {0, 0, 0}, "red_dark"},
	{"Tail", "Tail4Flesh", "Tail4", {0, 0, 0}, {0.44, 1.013, 0.44}, {0, 0, 0}, "red_hi"},
	{"Tail", "Tail4Underside", "Tail4", {0.055, 0, 0.077}, {0.286, 0.9, 0.308}, {0, 0, 0}, "red_dark"},
	{"Tail", "Tail5Flesh", "Tail5", {0, 0, 0}, {0.3, 0.81, 0.3}, {0, 0, 0}, "red"},
	{"Tail", "Tail5Underside", "Tail5", {0.037, 0, 0.052}, {0.195, 0.72, 0.21}, {0, 0, 0}, "red_dark"},
	{"Tail", "TailClaw", "Tail5", {0, -0.55, 0}, {0.16, 0.6, 0.16}, {0, 0, 0}, "claw"},
	{"Tail", "TailClawTip", "Tail5", {0, -0.85, 0.02}, {0.08, 0.28, 0.08}, {0, 0, 0}, "claw_tip"},
}

-- 6. TAIL CHAIN ---------------------------------------------------------------
-- { length, radius, joint rotation (deg) }; segments hang along -Y from their top end
local TAIL_ROOT_PART, TAIL_ROOT_POS = "Torso", {-0.25, -0.8, 0.5}
local TAIL = {
	{ 0.95, 0.46, {-88, 0, -16} },
	{ 0.95, 0.38, {24, 0, -16} },
	{ 0.9, 0.3, {28, 0, -10} },
	{ 0.75, 0.22, {14, 0, 0} },
	{ 0.6, 0.15, {-88, 0, 30} },
}

-- 7. BUILD --------------------------------------------------------------------
local function v3(t)
	return Vector3.new(t[1], t[2], t[3])
end

local function angles(t)
	return CFrame.Angles(math.rad(t[1]), math.rad(t[2]), math.rad(t[3]))
end

local function getSelectedR6()
	local ok, selection = pcall(function()
		return game:GetService("Selection"):Get()
	end)
	local model = ok and selection[1]
	if model and model:IsA("Model") and model:FindFirstChildOfClass("Humanoid") and model:FindFirstChild("Torso") then
		return model
	end
	return nil
end

local function makeBasePart(name, parent)
	local p = Instance.new("Part")
	p.Name = name
	p.Size = R6_SIZES[name]
	p.TopSurface = Enum.SurfaceType.Smooth
	p.BottomSurface = Enum.SurfaceType.Smooth
	p.Color = PALETTE.red[1]
	p.CanCollide = (name == "Torso" or name == "Head")
	p.Parent = parent
	return p
end

local function buildRig()
	local model = Instance.new("Model")
	model.Name = CONFIG.MODEL_NAME
	for name in pairs(R6_SIZES) do
		makeBasePart(name, model)
	end
	model.PrimaryPart = model.HumanoidRootPart
	model.HumanoidRootPart.Transparency = 1
	local humanoid = Instance.new("Humanoid")
	humanoid.RigType = Enum.HumanoidRigType.R6
	humanoid.Parent = model
	for _, j in ipairs(JOINTS) do
		local m = Instance.new("Motor6D")
		m.Name = j[1]
		m.Part0 = model[j[2]]
		m.Part1 = model[j[3]]
		m.MaxVelocity = 0.1
		m.Parent = model[j[2]]
	end
	model.HumanoidRootPart.CFrame = CFrame.new(0, 3 * CONFIG.SCALE, 0)
	model.Parent = workspace
	return model
end

local function applyJoints(model)
	for _, j in ipairs(JOINTS) do
		local m = model[j[2]]:FindFirstChild(j[1])
		if m then
			local rot = ROTATIONS[j[6]]
			m.C0 = CFrame.new(v3(j[4])) * rot
			m.C1 = CFrame.new(v3(j[5])) * rot
		end
	end
end

local function stripHumanLook(model)
	for _, d in ipairs(model:GetDescendants()) do
		if d:IsA("Accessory") or d:IsA("Shirt") or d:IsA("Pants") or d:IsA("ShirtGraphic")
			or d:IsA("CharacterMesh") or d:IsA("BodyColors")
			or (d:IsA("Decal") and d.Parent and d.Parent.Name == "Head")
			or (d:IsA("SpecialMesh") and d.Parent and d.Parent.Name == "Head") then
			d:Destroy()
		end
	end
end

local function makeTail(model, shell)
	local folder = Instance.new("Folder")
	folder.Name = "TailJoints"
	folder.Parent = shell
	local parent, prevLen = model[TAIL_ROOT_PART], nil
	for i, seg in ipairs(TAIL) do
		local part = Instance.new("Part")
		part.Name = "Tail" .. i
		part.Size = Vector3.new(seg[2], seg[1], seg[2])
		part.Transparency = 1
		part.CanCollide, part.CanTouch, part.CanQuery, part.Massless = false, false, false, true
		local c0 = (prevLen and CFrame.new(0, -prevLen / 2, 0) or CFrame.new(v3(TAIL_ROOT_POS))) * angles(seg[3])
		local c1 = CFrame.new(0, seg[1] / 2, 0)
		part.CFrame = parent.CFrame * c0 * c1:Inverse()
		part.Parent = folder
		local m = Instance.new("Motor6D")
		m.Name = "TailJoint" .. i
		m.Part0, m.Part1, m.C0, m.C1 = parent, part, c0, c1
		m.Parent = parent
		parent, prevLen = part, seg[1]
	end
	return folder
end

local function makePiece(model, shell, spec)
	local group, name, baseName, pos, size, rot, colorKey = table.unpack(spec)
	local base = model:FindFirstChild(baseName, true)
	if not base then
		warn("[RedCreature] missing base part " .. baseName .. " for " .. name)
		return
	end
	local folder = shell:FindFirstChild(group)
	if not folder then
		folder = Instance.new("Folder")
		folder.Name = group
		folder.Parent = shell
	end
	local look = PALETTE[colorKey]
	local offset = CFrame.new(v3(pos)) * angles(rot)
	local p = Instance.new("Part")
	p.Name = name
	p.Size = v3(size)
	p.Color, p.Material = look[1], look[2]
	p.CanCollide, p.CanTouch, p.CanQuery, p.Massless = false, false, false, true
	p.CFrame = base.CFrame * offset
	local mesh = Instance.new("SpecialMesh")
	mesh.MeshType = Enum.MeshType.Sphere
	mesh.Parent = p
	local weld = Instance.new("Weld")
	weld.Name = "ShellWeld"
	weld.Part0, weld.Part1, weld.C0 = base, p, offset
	weld.Parent = p
	p.Parent = folder
end

-- 8. RAGDOLL ON DEATH + TAIL SWAY -----------------------------------------------
local RAGDOLL_SOURCE = [[
local model = script.Parent
local humanoid = model:WaitForChild("Humanoid")
humanoid.BreakJointsOnDeath = false -- keep the creature shell welded on
humanoid.Died:Connect(function()
	for _, m in ipairs(model:GetDescendants()) do
		if m:IsA("Motor6D") and m.Name ~= "RootJoint" then
			local a0 = Instance.new("Attachment")
			a0.CFrame = m.C0
			a0.Parent = m.Part0
			local a1 = Instance.new("Attachment")
			a1.CFrame = m.C1
			a1.Parent = m.Part1
			local socket = Instance.new("BallSocketConstraint")
			socket.Attachment0, socket.Attachment1 = a0, a1
			socket.LimitsEnabled, socket.TwistLimitsEnabled = true, true
			socket.UpperAngle = 70
			socket.Parent = m.Part0
			m.Enabled = false
			if m.Part1.Name:sub(1, 4) ~= "Tail" then
				m.Part1.CanCollide = true
			end
		end
	end
end)
]]

-- Runs on every client (RunContext = Client), so everyone sees the sway.
local TAIL_SWAY_SOURCE = [[
local RunService = game:GetService("RunService")
local model = script.Parent
local joints = {}
for _, d in ipairs(model:GetDescendants()) do
	if d:IsA("Motor6D") and d.Name:match("^TailJoint") then
		joints[tonumber(d.Name:match("%d+"))] = d
	end
end
local t = 0
RunService.Stepped:Connect(function(_, dt)
	t += dt
	local hrp = model:FindFirstChild("HumanoidRootPart")
	local speed = hrp and hrp.AssemblyLinearVelocity.Magnitude or 0
	local amp = math.rad(4 + math.min(speed, 20) * 0.6)
	for i, joint in pairs(joints) do
		local phase = t * (2 + speed * 0.08) - i * 0.7
		joint.Transform = CFrame.Angles(math.sin(phase) * amp * 0.5, 0, math.sin(phase * 0.8) * amp)
	end
end)
]]

local function addScripts(model)
	if CONFIG.RAGDOLL_ON_DEATH and not model:FindFirstChild("RagdollOnDeath") then
		local s = Instance.new("Script")
		s.Name = "RagdollOnDeath"
		s.Source = RAGDOLL_SOURCE
		s.Parent = model
	end
	if CONFIG.TAIL_SWAY and not model:FindFirstChild("TailSway") then
		local s = Instance.new("Script")
		s.Name = "TailSway"
		s.RunContext = Enum.RunContext.Client
		s.Source = TAIL_SWAY_SOURCE
		s.Parent = model
	end
end

local function build()
	local model = getSelectedR6()
	local isNew = model == nil
	if isNew then
		model = buildRig()
	else
		model:ScaleTo(1)
	end
	if CONFIG.ADJUST_JOINTS then
		applyJoints(model)
	end
	-- let the joints settle the rest pose before pieces are placed
	model.HumanoidRootPart.Anchored = true
	for _, j in ipairs(JOINTS) do
		local m = model[j[2]]:FindFirstChild(j[1])
		if m then
			m.Part1.CFrame = m.Part0.CFrame * m.C0 * m.C1:Inverse()
		end
	end

	local old = model:FindFirstChild("CreatureShell")
	if old then
		old:Destroy()
	end
	local shell = Instance.new("Model")
	shell.Name = "CreatureShell"
	shell.Parent = model
	makeTail(model, shell)
	for _, spec in ipairs(PIECES) do
		makePiece(model, shell, spec)
	end

	stripHumanLook(model)
	if CONFIG.HIDE_BASE_BODY then
		for name in pairs(R6_SIZES) do
			model[name].Transparency = 1
		end
	end
	local humanoid = model:FindFirstChildOfClass("Humanoid")
	humanoid.DisplayDistanceType = Enum.HumanoidDisplayDistanceType.None
	humanoid.BreakJointsOnDeath = not CONFIG.RAGDOLL_ON_DEATH
	addScripts(model)

	model.HumanoidRootPart.Anchored = CONFIG.ANCHORED
	model:ScaleTo(CONFIG.SCALE)
	print(("[RedCreature] built %d pieces on %s"):format(#PIECES, model:GetFullName()))
	return model
end

build()

-- 9. ANIMATION NOTES -------------------------------------------------------------
--[[
	• All six R6 Motor6Ds keep their standard names and Part0/Part1, so the default R6
	  Animate script (idle/walk/run/jump/fall/climb) and any R6 animation play unchanged.
	• The hunch lives in the joint C0s (head low + forward, shoulders wide + forward).
	  Animations write Motor6D.Transform on top of C0, so the posture survives every animation.
	• Every creature piece is welded to exactly one R6 part (or a tail segment), so nothing
	  spans two limbs and nothing blocks arm/leg rotation. Pieces are Massless + CanCollide off.
	• The tail is a Motor6D chain (TailJoint1..5). The Animation Editor sees these joints, so
	  attack/idle animations can key the tail. TailSway only runs while no animation drives it
	  (an animation that keys a tail joint overrides it for that frame).
	• Death: BreakJointsOnDeath is off and RagdollOnDeath swaps Motor6Ds for BallSocketConstraints,
	  so the shell stays attached and the body collapses as one creature.
	• Knockback: apply velocity to HumanoidRootPart as usual; the shell is massless, so the
	  creature's physics behave like a normal R6 character.
]]
