--[[
	RED CREATURE — R6 build script (GENERATED by tools/build.py; edit the spec, not this file)

	HOW TO USE (Roblox Studio):
	  • New creature: paste this whole file into the Command Bar (View → Command Bar) and press Enter.
	    A model named CONFIG.MODEL_NAME appears at the origin.
	  • Convert an existing R6 rig: select the rig in the Explorer first, then run it.
	  • Player character: rename the result "StarterCharacter" and move it into StarterPlayer.
	    Copy the "Animate" LocalScript from your own character (Play → Workspace → <you>) into it.

	LAYOUT OF THIS FILE
	  1. CONFIG
	  2. MATERIALS / COLORS
	  3. R6 BASE BODY
	  4. JOINTS (Motor6Ds) — standard R6 names + hierarchy, hunch baked into C0
	  5. CREATURE GEOMETRY — head, eyes, torso, beige flesh, chest cavity, arms, legs, tail
	  6. TAIL CHAIN (animatable Motor6Ds)
	  7. BUILD (welds every piece to its R6 body part)
	  8. RAGDOLL ON DEATH + TAIL SWAY
	  9. ANIMATION NOTES
]]

-- 1. CONFIG ------------------------------------------------------------------
local CONFIG = {
	MODEL_NAME = "RedCreature",
	SCALE = 1.35,             -- whole-rig scale via Model:ScaleTo (1 = classic R6 size)
	HIDE_BASE_BODY = true,    -- R6 parts stay (joints, physics) but turn invisible
	ADJUST_JOINTS = true,     -- apply the hunched joint layout from section 4
	RAGDOLL_ON_DEATH = true,
	TAIL_SWAY = true,
	ANCHORED = false,
}

-- 2. MATERIALS / COLORS --------------------------------------------------------
local PALETTE = {
--@PALETTE@
}

-- 3. R6 BASE BODY --------------------------------------------------------------
local R6_SIZES = {
	HumanoidRootPart = Vector3.new(2, 2, 1),
	Torso = Vector3.new(2, 2, 1),
	Head = Vector3.new(2, 1, 1),
	["Right Arm"] = Vector3.new(1, 2, 1),
	["Left Arm"] = Vector3.new(1, 2, 1),
	["Right Leg"] = Vector3.new(1, 2, 1),
	["Left Leg"] = Vector3.new(1, 2, 1),
}

-- 4. JOINTS -------------------------------------------------------------------
-- { name, Part0, Part1, C0 position, C1 position, rotation }
local ROTATIONS = {
	root = CFrame.new(0, 0, 0, -1, 0, 0, 0, 0, 1, 0, 1, 0),
	right = CFrame.new(0, 0, 0, 0, 0, 1, 0, 1, 0, -1, 0, 0),
	left = CFrame.new(0, 0, 0, 0, 0, -1, 0, 1, 0, 1, 0, 0),
}
local JOINTS = {
--@JOINTS@
}

-- 5. CREATURE GEOMETRY ---------------------------------------------------------
-- { group, name, attached R6 part, position, size, rotation (deg XYZ), palette key }
-- Every piece is an ellipsoid (Part + Sphere SpecialMesh) welded to its body part,
-- so it follows that part through every animation.
local PIECES = {
--@PIECES@
}

-- 6. TAIL CHAIN ---------------------------------------------------------------
-- { length, radius, joint rotation (deg) }; segments hang along -Y from their top end
local TAIL_ROOT_PART, TAIL_ROOT_POS = --@TAIL_ROOT@
local TAIL = {
--@TAIL@
}

-- 7. BUILD --------------------------------------------------------------------
local function v3(t)
	return Vector3.new(t[1], t[2], t[3])
end

local function angles(t)
	return CFrame.Angles(math.rad(t[1]), math.rad(t[2]), math.rad(t[3]))
end

local function getSelectedR6()
	local ok, selection = pcall(function()
		return game:GetService("Selection"):Get()
	end)
	local model = ok and selection[1]
	if model and model:IsA("Model") and model:FindFirstChildOfClass("Humanoid") and model:FindFirstChild("Torso") then
		return model
	end
	return nil
end

local function makeBasePart(name, parent)
	local p = Instance.new("Part")
	p.Name = name
	p.Size = R6_SIZES[name]
	p.TopSurface = Enum.SurfaceType.Smooth
	p.BottomSurface = Enum.SurfaceType.Smooth
	p.Color = PALETTE.red[1]
	p.CanCollide = (name == "Torso" or name == "Head")
	p.Parent = parent
	return p
end

local function buildRig()
	local model = Instance.new("Model")
	model.Name = CONFIG.MODEL_NAME
	for name in pairs(R6_SIZES) do
		makeBasePart(name, model)
	end
	model.PrimaryPart = model.HumanoidRootPart
	model.HumanoidRootPart.Transparency = 1
	local humanoid = Instance.new("Humanoid")
	humanoid.RigType = Enum.HumanoidRigType.R6
	humanoid.Parent = model
	for _, j in ipairs(JOINTS) do
		local m = Instance.new("Motor6D")
		m.Name = j[1]
		m.Part0 = model[j[2]]
		m.Part1 = model[j[3]]
		m.MaxVelocity = 0.1
		m.Parent = model[j[2]]
	end
	model.HumanoidRootPart.CFrame = CFrame.new(0, 3 * CONFIG.SCALE, 0)
	model.Parent = workspace
	return model
end

local function applyJoints(model)
	for _, j in ipairs(JOINTS) do
		local m = model[j[2]]:FindFirstChild(j[1])
		if m then
			local rot = ROTATIONS[j[6]]
			m.C0 = CFrame.new(v3(j[4])) * rot
			m.C1 = CFrame.new(v3(j[5])) * rot
		end
	end
end

local function stripHumanLook(model)
	for _, d in ipairs(model:GetDescendants()) do
		if d:IsA("Accessory") or d:IsA("Shirt") or d:IsA("Pants") or d:IsA("ShirtGraphic")
			or d:IsA("CharacterMesh") or d:IsA("BodyColors")
			or (d:IsA("Decal") and d.Parent and d.Parent.Name == "Head")
			or (d:IsA("SpecialMesh") and d.Parent and d.Parent.Name == "Head") then
			d:Destroy()
		end
	end
end

local function makeTail(model, shell)
	local folder = Instance.new("Folder")
	folder.Name = "TailJoints"
	folder.Parent = shell
	local parent, prevLen = model[TAIL_ROOT_PART], nil
	for i, seg in ipairs(TAIL) do
		local part = Instance.new("Part")
		part.Name = "Tail" .. i
		part.Size = Vector3.new(seg[2], seg[1], seg[2])
		part.Transparency = 1
		part.CanCollide, part.CanTouch, part.CanQuery, part.Massless = false, false, false, true
		local c0 = (prevLen and CFrame.new(0, -prevLen / 2, 0) or CFrame.new(v3(TAIL_ROOT_POS))) * angles(seg[3])
		local c1 = CFrame.new(0, seg[1] / 2, 0)
		part.CFrame = parent.CFrame * c0 * c1:Inverse()
		part.Parent = folder
		local m = Instance.new("Motor6D")
		m.Name = "TailJoint" .. i
		m.Part0, m.Part1, m.C0, m.C1 = parent, part, c0, c1
		m.Parent = parent
		parent, prevLen = part, seg[1]
	end
	return folder
end

local function makePiece(model, shell, spec)
	local group, name, baseName, pos, size, rot, colorKey = table.unpack(spec)
	local base = model:FindFirstChild(baseName, true)
	if not base then
		warn("[RedCreature] missing base part " .. baseName .. " for " .. name)
		return
	end
	local folder = shell:FindFirstChild(group)
	if not folder then
		folder = Instance.new("Folder")
		folder.Name = group
		folder.Parent = shell
	end
	local look = PALETTE[colorKey]
	local offset = CFrame.new(v3(pos)) * angles(rot)
	local p = Instance.new("Part")
	p.Name = name
	p.Size = v3(size)
	p.Color, p.Material = look[1], look[2]
	p.CanCollide, p.CanTouch, p.CanQuery, p.Massless = false, false, false, true
	p.CFrame = base.CFrame * offset
	local mesh = Instance.new("SpecialMesh")
	mesh.MeshType = Enum.MeshType.Sphere
	mesh.Parent = p
	local weld = Instance.new("Weld")
	weld.Name = "ShellWeld"
	weld.Part0, weld.Part1, weld.C0 = base, p, offset
	weld.Parent = p
	p.Parent = folder
end

-- 8. RAGDOLL ON DEATH + TAIL SWAY -----------------------------------------------
local RAGDOLL_SOURCE = [[
local model = script.Parent
local humanoid = model:WaitForChild("Humanoid")
humanoid.BreakJointsOnDeath = false -- keep the creature shell welded on
humanoid.Died:Connect(function()
	for _, m in ipairs(model:GetDescendants()) do
		if m:IsA("Motor6D") and m.Name ~= "RootJoint" then
			local a0 = Instance.new("Attachment")
			a0.CFrame = m.C0
			a0.Parent = m.Part0
			local a1 = Instance.new("Attachment")
			a1.CFrame = m.C1
			a1.Parent = m.Part1
			local socket = Instance.new("BallSocketConstraint")
			socket.Attachment0, socket.Attachment1 = a0, a1
			socket.LimitsEnabled, socket.TwistLimitsEnabled = true, true
			socket.UpperAngle = 70
			socket.Parent = m.Part0
			m.Enabled = false
			if m.Part1.Name:sub(1, 4) ~= "Tail" then
				m.Part1.CanCollide = true
			end
		end
	end
end)
]]

-- Runs on every client (RunContext = Client), so everyone sees the sway.
local TAIL_SWAY_SOURCE = [[
local RunService = game:GetService("RunService")
local model = script.Parent
local joints = {}
for _, d in ipairs(model:GetDescendants()) do
	if d:IsA("Motor6D") and d.Name:match("^TailJoint") then
		joints[tonumber(d.Name:match("%d+"))] = d
	end
end
local t = 0
RunService.Stepped:Connect(function(_, dt)
	t += dt
	local hrp = model:FindFirstChild("HumanoidRootPart")
	local speed = hrp and hrp.AssemblyLinearVelocity.Magnitude or 0
	local amp = math.rad(4 + math.min(speed, 20) * 0.6)
	for i, joint in pairs(joints) do
		local phase = t * (2 + speed * 0.08) - i * 0.7
		joint.Transform = CFrame.Angles(math.sin(phase) * amp * 0.5, 0, math.sin(phase * 0.8) * amp)
	end
end)
]]

local function addScripts(model)
	if CONFIG.RAGDOLL_ON_DEATH and not model:FindFirstChild("RagdollOnDeath") then
		local s = Instance.new("Script")
		s.Name = "RagdollOnDeath"
		s.Source = RAGDOLL_SOURCE
		s.Parent = model
	end
	if CONFIG.TAIL_SWAY and not model:FindFirstChild("TailSway") then
		local s = Instance.new("Script")
		s.Name = "TailSway"
		s.RunContext = Enum.RunContext.Client
		s.Source = TAIL_SWAY_SOURCE
		s.Parent = model
	end
end

local function build()
	local model = getSelectedR6()
	local isNew = model == nil
	if isNew then
		model = buildRig()
	else
		model:ScaleTo(1)
	end
	if CONFIG.ADJUST_JOINTS then
		applyJoints(model)
	end
	-- let the joints settle the rest pose before pieces are placed
	model.HumanoidRootPart.Anchored = true
	for _, j in ipairs(JOINTS) do
		local m = model[j[2]]:FindFirstChild(j[1])
		if m then
			m.Part1.CFrame = m.Part0.CFrame * m.C0 * m.C1:Inverse()
		end
	end

	local old = model:FindFirstChild("CreatureShell")
	if old then
		old:Destroy()
	end
	local shell = Instance.new("Model")
	shell.Name = "CreatureShell"
	shell.Parent = model
	makeTail(model, shell)
	for _, spec in ipairs(PIECES) do
		makePiece(model, shell, spec)
	end

	stripHumanLook(model)
	if CONFIG.HIDE_BASE_BODY then
		for name in pairs(R6_SIZES) do
			model[name].Transparency = 1
		end
	end
	local humanoid = model:FindFirstChildOfClass("Humanoid")
	humanoid.DisplayDistanceType = Enum.HumanoidDisplayDistanceType.None
	humanoid.BreakJointsOnDeath = not CONFIG.RAGDOLL_ON_DEATH
	addScripts(model)

	model.HumanoidRootPart.Anchored = CONFIG.ANCHORED
	model:ScaleTo(CONFIG.SCALE)
	print(("[RedCreature] built %d pieces on %s"):format(#PIECES, model:GetFullName()))
	return model
end

build()

-- 9. ANIMATION NOTES -------------------------------------------------------------
--[[
	• All six R6 Motor6Ds keep their standard names and Part0/Part1, so the default R6
	  Animate script (idle/walk/run/jump/fall/climb) and any R6 animation play unchanged.
	• The hunch lives in the joint C0s (head low + forward, shoulders wide + forward).
	  Animations write Motor6D.Transform on top of C0, so the posture survives every animation.
	• Every creature piece is welded to exactly one R6 part (or a tail segment), so nothing
	  spans two limbs and nothing blocks arm/leg rotation. Pieces are Massless + CanCollide off.
	• The tail is a Motor6D chain (TailJoint1..5). The Animation Editor sees these joints, so
	  attack/idle animations can key the tail. TailSway only runs while no animation drives it
	  (an animation that keys a tail joint overrides it for that frame).
	• Death: BreakJointsOnDeath is off and RagdollOnDeath swaps Motor6Ds for BallSocketConstraints,
	  so the shell stays attached and the body collapses as one creature.
	• Knockback: apply velocity to HumanoidRootPart as usual; the shell is massless, so the
	  creature's physics behave like a normal R6 character.
]]
